
; ******************
; **              **
; **  GTIA: D0xx  **
; **              **
; ******************

TRIG0		=	$D010		; (R)  Joystick trigger 0
TRIG1		=	$D011		; (R)  Joystick trigger 1
TRIG2		=	$D012		; (R)  Joystick trigger 2
TRIG3		=	$D013		; (R)  Joystick trigger 3

PAL		=	$D014		; (R)  PAL /NTSC flag

COLPF1		=	$D017		; (W)  Color / luminance playfield one

PRIOR		=	$D01B		; (W)  Priority selection register
CONSOL		=	$D01F		;(R/W) Console buttons / speaker
