		; **********************************
		; **                              **
		; **  ATARI BASIC ROM: A000-BFFF  **
		; **                              **
		; **********************************

LOMEM		=	$80	; pointer to BASIC's low memory
VNTP		=	$82	; start of variable name table
VNTD		=	$84	; end of variable name table
VVTP		=	$86	; start of variable value table
STMTAB		=	$88	; start of the statement table
STMCUR		=	$8A	; current statement pointer
STARP		=	$8C	; strings/arrays pointer
RUNSTK		=	$8E	; runtime stack
MEMTOP		=	$90	; memtop
POKADR		=	$95	; address of last POKE location
DATAD		=	$B6	; data element being read
DATALN		=	$B7	; data statement line number
STOPLN		=	$BA	; line where the program was stopped
ERRSAVE		=	$C3	; number of the error code
PTABW		=	$C9	; number of columns between tab stops

		.org $A000
		.segment "A000BFFF"

		.include "../include/atari.inc"
		.include "../include/pokey.inc"

		.include "sourcebook.inc"

		; BasicString str - Output len-1 regular bytes and last byte OR'ed with 0x80
		.macro	BasicString stringval
		.repeat	.strlen (stringval)-1,i
		.byte	.strat (stringval,i)
		.endrep
		.byte	.strat (stringval,.strlen(stringval)-1) | $80
		.endmacro

		; WordBasicString adr,str - Output handler address and string
		.macro WordBasicString wordval,stringval
		.word wordval-1
		BasicString stringval
		.endmacro

COLDSTART:	LDA	LOADFLG		;Y IN MIDDLE OF LOAD
		BNE	@COLD1		; DO COLDSTART
		LDA	WARMST		; IF WARM START
		BNE	WARMSTART	; THEN BRANCH
@COLD1:		LDX	#$FF		; SET ENTRY STACK
		TXS			; TO TOS
		CLD			; CLEAR DECIMAL MODE

; XNEW - Execute NEW

XNEW:		LDX	LMADR		;LOAD LOW
		LDY	LMADR+1		;MEM VALUE
		STX	LOMEM		; SET LOMEM
		STY	LOMEM+1
		LDA	#0		; RESET MODIFIED
		STA	MEOLFLG		; EOL FLAG
		STA	LOADFLG		; RESET LOAD FLAG
		INY			; ALLOW 256 FOR OUTBUFF
		TXA			;VNTP

		LDX	#VNTP		; GET ZPG DISPC TO VNTP
@CS1:		STA	0,X		; SET TABLE ADR LOW
		INX
		STY	0,X		; SET TABLE ADR HIGH
		INX
		CPX	#MEMTOP+2	; AT LIMIT
		BCC	@CS1		; BR IF NOT

		LDX	#VVTP		; EXPAND VNT BY ONE
		LDY	#1		; FOR END OF VNT
		JSR	EXPLOW		; ZERO BYTE
		LDX	#STARP		; EXPAND STMT TBL
		LDY	#3		; BY 3 BYTES
		JSR	EXPLOW		; GO DO IT

		LDA	#0		; SET 0
		TAY
		STA	(VNTD),Y	; INTO VVTP
		STA	(STMCUR),Y	; INTO STMCUR+0
		INY
		LDA	#$80		; $80 INTO
		STA	(STMCUR),Y	; STMCUR+1
		INY
		LDA	#$03		; $03 INTO
		STA	(STMCUR),Y	; STMCUR+2

		LDA	#10		; SET PRINT TAB
		STA	PTABW		; WIDTH TO 10

; Warm Start
;	WARMSTART - BASIC RESTART
;	            DOES NOT DESTROY CURRENT PGM
WARMSTART:	JSR	RUNINIT		; INIT FOR RUN
SNX1:		JSR	CLSALL		; GO CLOSE DEVICE 1-7
SNX2:		JSR	SETDZ		; SET E/L DEVICE 0
		LDA	MEOLFLG		; IF AN EOL INSERTED
		BEQ	SNX3
		JSR	RSTSEOL		; THEN UN-INSERT IT
SNX3:		JSR	PREADY		; PRINT READY MESSAGE

;
; Syntax
;

;
; Editor - Get Lines of Input
;

SYNTAX:		LDA	LOADFLG		; IF LOAD IN PROGRESS
		BNE	COLDSTART	; GO DO COLDSTART
		LDX	#$FF		; RESTORE STACK
		TXS
		JSR	INTLBF		; GO INT LBUFF
		LDA	#EPCHAR		; ]
		STA	PROMPT
		.if	BASIC_REVISION = 1
		JSR	GLGO
		JSR	TSTBRK		; TEST BREAK
		BNE	SYNTAX		; BR IF BREAK
		.else
		jsr	GLGO2
		jsr	TSTBRK
		beq	SYNTAX
		.endif

		LDA	#0		; INIT CURRENT
		STA	CIX		;INPUT INDEX TO ZERO
		STA	MAXCIX
		STA	COX		;OUTPUT INDEX TO ZERO
		STA	DIRFLG		;SET DIRECT SMT
		STA	SVONTX		; SET SAVE ONT CIX
		STA	SVONTC
		STA	SVVVTE		; VALUE IN CASE
		LDA	VNTD		; OF SYNTAX ERROR
		STA	SVVNTP
		LDA	VNTD+1
		STA	SVVNTP+1

		JSR	SKBLANK		; SKIP BLANKS
		JSR	GETLNUM		;CONVERT AND PUT IN BUFFER
		JSR	_SETCODE	; SET DUMMY FOR LINE LENGTH
		LDA	BININT+1
		BPL	@SYN0
		STA	DIRFLG
@SYN0:		JSR	SKBLANKS	; SKIP BLANKS
		LDY	CIX		;GET INDEX
		STY	STMSTRT		;SAVE INCASE OF SYNTAX ERROR
		LDA	(INBUFF),Y	;GET NEXT CHAR
		CMP	#CR		;IS IT CR
		BNE	SYN1		;BR NOT CR
		BIT	DIRFLG		; IF NO LINE NO.
		BMI	SYNTAX		; THEN NO. DELETE
		JMP	SDEL		;GO DELETE STMT

_XIF:
SYN1:		LDA	COX		;SAVE COX
		STA	STMLBD		;AS PM TO STMT LENGTH BYTE
		JSR	_SETCODE	; DUMMY FOR STMT LENGTH

		JSR	SKBLANK		;GO SKIP BLANKS
		LDA	#>SNTAB		; SET UP FOR STMT
		LDY	#<SNTAB		;NAME SEARCH
		LDX	#2
		JSR	SEARCH		;AND DO IT
		STX	CIX
		LDA	STENUM		;GET STMT NUMBER
		JSR	_SETCODE	;GO SET CODE
		JSR	SKBLANK
		JSR	SYNENT		;AND GO SYNTAX HIM
		BCC	SYNOK		;BR IF OK SYNTAX
					;ELSE SYNTAX ERROR
		LDY	MAXCIX		; GET MAXCIX
		LDA	(INBUFF),Y	; LOAD MAXCIX CHAR
		CMP	#CR		; WAS IT CR
		BNE	@SYN3A		; BR IF NOT CR
		INY			; MOVE CR RIGHT ONE
		STA	(INBUFF),Y
		DEY			; THEN PUT A
		LDA	#' '		; BLANK IN ITS PLACE
@SYN3A:		ORA	#$80		; SET MAXCIX CHAR
		STA	(INBUFF),Y	; TO FLASH

		LDA	#$40		;INDICATE SYNTAX ERROR
		ORA	DIRFLG
		STA	DIRFLG		; IN DIRFLG
		LDY	STMSTRT		;RESTORE STMT START
		STY	CIX
		LDX	#3		;SET FOR FIRST STMT
		STX	STMLBD
		INX			;INC TO CODE
		STX	COX		;AND SET COX
		LDA	#CERR		; GARBAGE CODE
SYN3:		JSR	_SETCODE	;GO SET CODE

_XDATA:		LDY	CIX		;GET INDEX
		LDA	(INBUFF),Y	;GET INDEX CHAR
		INC	CIX		;INC TO NXT
		CMP	#CR		;IS IT CR
		BNE	SYN3		;BR IF NOT
		JSR	_SETCODE

SYNOK:		LDA	COX		; GET DISPL TO END OF STMT
		LDY	STMLBD
		STA	(OUTBUFF),Y	;SET LENGTH BYTE
		LDY	CIX		;GET INPUT DISPL
		DEY
		LDA	(INBUFF),Y	;GET LAST CHAR
		CMP	#CR		;IS IT CR
		BNE	SYN1		;BR IF NOT

		LDY	#2		; SET LINE LENGTH
		LDA	COX		; INTO STMT
		STA	(OUTBUFF),Y

		JSR	GETSTMT		;GO GET STMT
		LDA	#0
		BCS	@8
		JSR	GETLL		;GO GET LINE LENGTH
@8:		SEC
		SBC	COX		;ACU=LENGTH[OLD-NEW]
		BEQ	@10		; BR NEW=OLD
		BCS	@9		;BR OLD<NEW
					;OLD<NEW
		EOR	#$FF		;COMPLEMENT RESULT
		TAY
		INY
		LDX	#STMCUR		;POINT TO STMT CURRENT
		JSR	EXPLOW		;GO EXPAND
		LDA	SVESA		;RESET STMCUR
		STA	STMCUR
		LDA	SVESA+1
		STA	STMCUR+1
		BNE	@10

@9:		.if	BASIC_REVISION = 1
		PHA			; CONTRACT LENGTH
		JSR	GNXTL
		PLA
		TAY
		.else
		tay
		jsr	GNXTL
		.endif

		LDX	#STMCUR		;POINT TO STMT CURRENT
		JSR	CONTLOW1	;GO CONTRACT

@10:		LDY	COX		; STMT LENGTH
@11:		DEY			; MINUS ONE
		LDA	(LOMEM),Y	; GET BUFF CHAR
		STA	(STMCUR),Y	;PUT INTO STMT TBL
		TYA			; TEST END
		BNE	@11		; BR IF NOT
		BIT	DIRFLG		;TEST FOR SYNTAX ERROR
		BVC	L13		;BR IF NOT
		LDA	SVVVTE		; CONTRACT VVT
		ASL
		ASL
		ASL

		.if	BASIC_REVISION = 1
		TAY
		.endif

		LDX	#ENDVVT
		JSR	CONTLOW
		SEC
		LDA	VNTD		; CONTRACT VNT
		SBC	SVVNTP
		TAY
		LDA	VNTD+1
		SBC	SVVNTP+1
		LDX	#VNTD
		JSR	CONTRACT
		BIT	DIRFLG		; IF STMT NOT DIRECT
		BPL	@12		; THE BRANCH
		JSR	LDLINE		; ELSE LIST DIRECT LINE
		JMP	SYNTAX		; THEN BACK TO SYNTAX
@12:		JSR	LLINE		; LIST ENTIRE LINE

SYN9:		JMP	SYNTAX
L13:		BPL	SYN9
		JMP	EXECNL		; GO TO PROGRAM EXECUTOR

SDEL:		JSR	GETSTMT		; GO GET LINE
		BCS	SYN9		; BR NOT FOUND
		JSR	GETLL		;GO GET LINE LENGTH

		.if	BASIC_REVISION = 1
		PHA			; Y
		JSR	GNXTL
		PLA
		TAY
		.else
		tay
		jsr	GNXTL
		.endif

		LDX	#STMCUR		;GET STMCUR DISPL
		JSR	CONTLOW1	; GO DELETE
		JMP	SYNTAX		;GO FOR NEXT LINE

;
; Get a Line Number
;
;	GETLNUM - GET A LINE NO FROM ASCLT IN INBUFF
;		  TO BINARY INTO OUTBUFF
GETLNUM:	JSR	CVAFP		; GO CONVERT LINE #
		BCC	@GLNUM		; BR IF GOOD LINE #

@GLN1:		LDA	#0		; SET LINE #
		STA	CIX
		LDY	#$80		; =$8000
		BMI	@SLNUM

@GLNUM:		JSR	CVFPI		; CONVERT FP TO INT
		LDY	BININT+1	; LOAD RESULT
		BMI	@GLN1		; BR IF LNO>32767
		LDA	BININT

@SLNUM:		STY	TSLNUM+1	; SET LINE # HIGH
		STA	TSLNUM		; AND LOW
		JSR	_SETCODE	; OUTPUT LOW
		LDA	TSLNUM+1	; OUTPUT HI
		STA	BININT+1
		JMP	_SETCODE	; AND RETURN

; SYNENT - PERFORM LINE PRE-COMPILE

SYNENT:		LDY	#1		; GET PC HIGH
		LDA	(POKADR),Y
		STA	CPC+1		;SET PGM COUNTERS
		STA	SPC+1
		DEY
		LDA	(POKADR),Y
		STA	CPC
		STA	SPC
		.if	BASIC_REVISION = 1
		LDA	#0		;SET STKLVL
		STA	STKLVL		;SET STKLVL
		.else
		sty	STKLVL
		.endif
		LDA	COX		;MOVE
		STA	SOX		;COX TO SOX
		LDA	CIX		;MOVE
		STA	SIX		;CIX TO SIX

; NEXT		GET NEXT SYNTAX CODE
;		AS LONG AS NOT FAILING

NEXT:		JSR	NXSC		; GET NEXT CODE

		BMI	@ERNTV		; BR IF REL-NON-TERMINAL

		CMP	#1		; TEST CODE=1
		BCC	@4		; BR CODE=0 [ABS-NON-TERMINAL]
		BNE	@TSTSUC		; BR CODE >1

		JSR	@4		; CODE=1 [EXTERNAL SUBROUTINE]
		.if	BASIC_REVISION = 1
		BCC	NEXT		; BR IF SUB REPORTS SUCCESS
		JMP	FAIL		; ELSE GO TO FAIL CODE
		.else
		jmp	FAIL2
		.endif

@TSTSUC:	CMP	#5		; TEST CODE = 5
		BCC	POP		; CODE = [2,3,or 4] POP UP TO
					; NEXT SYNTAX CODE
		JSR	TERMTST		; CODE=5 GO TEST TERMINAL

		.if	BASIC_REVISION = 1
		BCC	NEXT		; BR IF SUCCESS
		JMP	FAIL		; ELSE GO TO FAIL CODE
		.else
		jmp	FAIL2
		.endif

@ERNTV:		SEC			; RELATIVE NON TERMINAL

		.if	BASIC_REVISION = 1
		LDX	#0		; TOKEN MINUS
		.endif

		SBC	#$C1
		BCS	@ERN1		; BR IF RESULT PLUS
		LDX	#$FF		; ADD A MINUS
@ERN1:		CLC
		ADC	CPC		; RESULT PLUS CPC
		PHA			; IS NEW CPC-1
		TXA
		ADC	CPC+1
		PHA			; SAVE NEW PC HIGH
		JMP	_PUSH

@4:		JSR	NXSC		; GET NEXT CODE
		PHA			; SAVE ON STACK
		JSR	NXSC		; GET NEXT CODE
		PHA			; SAVE ON STACK
		BCC	_PUSH		; BR IF CODE =0
		PLA			; EXCHANGE TOP
		TAY			; 2 ENTRIES ON
		PLA			; CPU STACK
		TAX
		TYA
		PHA
		TXA
		PHA
NRTS1:		RTS			; ELSE GOTO EXTERNAL SRT VIA RTS

; PUSH		PUSH TO NEXT STACK LEVEL

_PUSH:		LDX	STKLVL		; GET STACK LEVEL
		INX			; PLUS 4
		INX
		INX
		INX
		BEQ	@SSTB		;BR STACK TOO  BIG
		STX	STKLVL		; SAVE NEW STACK LEVEL

		LDA	CIX		; CIX TO
		STA	SIX,X		; STACK IX
		LDA	COX		; COX TO
		STA	SOX,X		; STACK OX
		LDA	CPC		; CPC TO
		STA	SPC,X		; STACK CPC
		LDA	CPC+1
		STA	SPC+1,X

		PLA			; MOVE STACKED
		STA	CPC+1		; PC TO CPC
		PLA
		STA	CPC
		JMP	NEXT		; GO FOR NEXT

@SSTB:		JMP	ERLTL

; POP		LOAD CPC FROM STACK PC
;		AND DECREMENT TO PREVIOUS STACK LEVEL

POP:		LDX	STKLVL		; GET STACK LEVEL

		.if	BASIC_REVISION = 1
		BNE	@POP1		; BR NOT TOP OF STACK
		RTS			; TO SYNTAX CALLER
		.else
		beq	NRTS1
		.endif

@POP1:		LDA	SPC,X		; MOVE STACK PC
		STA	CPC		; TO CURRENT PC
		LDA	SPC+1,X
		STA	CPC+1

		DEX			; X=X-4
		DEX
		DEX
		DEX
		STX	STKLVL

FAIL2:		BCS	FAIL		; BR IF CALLER FAILING
		JMP	NEXT		; ELSE GO TO NEXT

; FAIL
;		TERMINAL FAILED
;		LOOK FOR ALTERNATIVE [OR] OR
;		A RETURN INDICATOR
;
FAIL:		JSR	NXSC		; GET NEXT CODE

		BMI	FAIL		; BR IF RNTV

		CMP	#2		; TEST CODE =2
		BCS	@TSTOR		; BR IF POSSIBLE OR

		JSR	_INCCPC		; CODE = 0 OR 1
		JSR	_INCCPC		; INC PC BY TWO
		BNE	FAIL		; AND CONTINUE FAIL PROCESS

@TSTOR:		CMP	#3		; TEXT CODE=3
		BEQ	POP		; BR CODE =3 [RETURN]
		BCS	FAIL		; CODE>3 [RNTV] CONTINUE

		LDA	CIX		; IF THIS CIX
		CMP	MAXCIX		; IS A NEW MAX
		BCC	@SCIX
		STA	MAXCIX		; THEN SET NEW MAX
@SCIX:		LDX	STKLVL		; CODE=2 [OR]
		LDA	SIX,X		; MOVE STACK INDEXES
		STA	CIX		; TO CURRENT INDEXES
		LDA	SOX,X
		STA	COX
		JMP	NEXT		; TRY FOR SUCCESS HERE

; Increment CPC

; INCCPC - INC CPC BY ONE

_INCCPC:	INC	CPC
		BNE	@ICPCR
		INC	CPC+1
@ICPCR:		RTS


; NXSC - GET NEXT SYNTAX CODE

NXSC:		JSR	_INCCPC		; INC PC
		LDX	#0
		LDA	(CPC,X)		; GET NEXT CODE
		RTS			; RETURN

; TERMTST - TEST A TERMINAL CODE

TERMTST:	CMP	#_CHNG		; TEST CODE=F
		BEQ	ECHNG		; BR CODE = F
		BCS	SRCONT		; BR CODE > F

		.if	BASIC_REVISION > 1
		cmp	#_UNKN		; TEST CODE=D
		bne	@TT1
		jsr	_INCCPC		; NEXT CPC
		jmp	_SRCNT1
		.endif

@TT1:		PLA			; POP RTN ADR
		PLA
		LDA	#<(_EXP-1)	; PUSH EXP ADR
		PHA			; FOR SPECIAL
		LDA	#>(_EXP-1)	; EXP ANTV CALL
		PHA
		JMP	_PUSH		; GO PUSH

; ECHNG - EXTERNAL CODE TO CHANGE COX -1

ECHNG:		JSR	_INCCPC		; INC PC TO CODE
		LDY	#0
		LDA	(CPC),Y		; GET CODE
		LDY	COX		; GET COX
		DEY			; MINUS 1
		STA	(OUTBUFF),Y	; SET NEW CODE
		CLC			; SET SUCCESS
_ECRTS:		RTS			; RETURN

_SETCODE:	LDY	COX		;GET COX
		STA	(OUTBUFF),Y	;SET CHAR
		INC	COX		;INC COD

		.if	BASIC_REVISION = 1
		BEQ	@SCOVF		;BR IF NOT ZERO
		RTS			;DONE
		.else
		bne	_ECRTS
		.endif

@SCOVF:		JMP	ERLTL		;GO TO LINE TOO LONG ERR

; Exits for IF and REM

_EIF:		LDX	#$FF		; RESET STACK
		TXS
		LDA	COX		; SET STMT LENGTH
		LDY	STMLBD
		STA	(OUTBUFF),Y
		JMP	_XIF		; GO CONTINUE IF
_EREM:
_EDATA:		LDX	#$FF		; RESET STACK
		TXS
		JMP	_XDATA		;GO CONTINUE DATA

; SRCONT - SEARCH OP NAME TABLE AND TEST RESULT

SRCONT:		JSR	SKBLANK		; SKIP BLANKS
_SRCNT1:	LDA	CIX		; GET CURRENT INPUT INDEX
		CMP	SVONTX		; COMPARE WITH SAVED IX
		BEQ	@SONT1		; BR IF SAVED IX SAME
		STA	SVONTX		; SAVE NEW IX

		LDA	#>OPNTAB	; SET UP FOR ONT
		LDY	#<OPNTAB	; SEARCH
		LDX	#0
		JSR	SEARCH		; GO SEARCH
		BCS	@SONF		; BR NOT FOUND
		STX	SVONTL		; SAVE NEW CIX

		.if	BASIC_REVISION = 1
		CLC
		.endif

		LDA	STENUM		; ADD $10 TO
		ADC	#$10		; ENTRY NUMBER TO
		STA	SVONTC		; GET OPERATOR CODE

@SONT1:		LDY	#0
		LDA	($9D),Y		; GET SYNTAX REQ CODE
		CMP	SVONTC		; DOES IT MATCH THE FOUND
		BEQ	@SONT2		; BR IF MATCH
		CMP	#CNFNP		; WAS REQ NFNP

		.if	BASIC_REVISION = 1
		BNE	@SONTF		; BR IF NOT
		LDA	SVONTC		; GET WHAT WE GOT
		CMP	#CNFNP		; IS IT NFNA
		BCS	@SONTS		; BR IF IT IS

@SONTF:		SEC			; REPORT FAIL
		RTS
@SONTS:		LDA	SVONTC		; GET REAL CODE
		.else
		bne	@SONF1
		lda	SVONTC
		cmp	#CNFNP
		bcc	@SONF1
		.endif

@SONT2:		JSR	_SETCODE		; GO SET CODE
		LDX	SVONTL		; INC CIX BY
		STX	CIX
		CLC			; REPORT SUCCESS
		RTS			; DONE

@SONF:		LDA	#0		; SET ZERO AS
		STA	SVONTC		; SAVED CODE
@SONF1:		SEC
		RTS			; DONE

; _TNVAR - EXTERNAL SUBROUTINE FOR TNVAR & TSVAR

_TNVAR:		LDA	#0		; SET NUMERIC TEST
		BEQ	_TVAR

_TSVAR:		LDA	#$80		; SET STR TEST
_TVAR:		STA	TVTYPE		; SAVE TEST TYPE
		JSR	SKPBLANK	; SKIP LEADING BLANKS
		LDA	CIX		; GET INDEX
		STA	TVSCIX		; FOR SAVING

		JSR	_TSALPH		; GO TEST FIRST CHAR
		BCS	@TVFAIL		; BR NOT ALPHA
		JSR	SRCONT		; IF THIS IS A
		LDA	SVONTC		; RESVD NAME
		BEQ	@TV1		; BR NOT RSVDNAME
		LDY	SVONTL		; IF NEXT CHAR AFTER
		LDA	(INBUFF),Y	; RESERVED NAME
		CMP	#'0'		; NOT ALARM NUMERIC
		BCC	@TVFAIL		; THEN ERROR

@TV1:		INC	CIX		; INC TO NEXT CHAR
		JSR	_TSALPH		; TEST ALPHA
		BCC	@TV1		; BR IF ALPHA
		JSR	__DBAF		; TRY NUMBER
		BCC	@TV1		; BR IF NUMBER

		LDA	(INBUFF),Y	; GET OFFENDING CHAR
		CMP	#'$'		; IS IT $
		BEQ	@TVSTR		; BR IF $ [STRING]
		BIT	TVTYPE		; THIS A NVAR SEARCH
		BPL	@TVOK		; BR IF NVAR

@TVFAIL:	SEC			; SET FAIL CODE
		RTS			; DONE

@TVSTR:		BIT	TVTYPE		; TEST SVAR SEARCH
		BPL	@TVFAIL		; BR IF SVAR
		INY			; INC OVER $
		BNE	@TVOK2		; BR ALWAYS

@TVOK:		LDA	(INBUFF),Y	; GET NEXT CHAR
		CMP	#'('		; IS IT PAREN
		BNE	@TVOK2		; BR NOT PAREN
		INY			; INC OVER PARAN
		LDA	#$40		; OR IN ARRAY
		ORA	TVTYPE		; CODE TO TVTYPE
		STA	TVTYPE

@TVOK2:		LDA	TVSCIX		; GET SAVED CIX
		STA	CIX		; PUT BACK
		STY	TVSCIX		; SAVE NEW CIX

		LDA	VNTP+1		; SEARCH VNT
		LDY	VNTP		; FOR THIS GUY
		LDX	#0
		JSR	SEARCH
@TVRS:		BCS	@TVS0		; BR NOT FOUND
		CPX	TVSCIX		; FOUND RIGHT ONE
		BEQ	@TVSUC		; BR IF YES
		JSR	SRCNXT		; GO SEARCH MORE
		JMP	@TVRS		; TEST THIS RESULT

@TVS0:		SEC			; SIGH:
		LDA	TVSCIX		; VAR LENGTH IS
		SBC	CIX		; NEW CIX-OLD CIX
		STA	CIX

		TAY			; GO EXPAND VNT
		LDX	#VNTD		; BY VAR LENGTH
		JSR	EXPLOW
		LDA	STENUM		; SET VARIABLE NUMBER
		STA	TVNUM

		LDY	CIX		; AND
		DEY
		LDX	TVSCIX		; GET DISPL TO EQU+1
		DEX
@TVS1:		LDA	LBUFF,X		; MOVE VAR TO
		STA	(SVESA),Y
		DEX
		DEY
		BPL	@TVS1

		LDY	CIX		;TURN ON MSB
		DEY			;OF LAST CHAR
		LDA	(SVESA),Y	;IN VTVT ENTRY
		ORA	#$80
		STA	(SVESA),Y

		LDY	#8		; THEN EXPAND
		LDX	#STMTAB		; VVT BY 8
		JSR	EXPLOW
		INC	SVVVTE		; INC VVT EXP SIZE

		LDY	#2		; CLEAR VALUE
		LDA	#0		; PART OF
@TVS1A:		STA	TVTYPE,Y	; ENTRY
		INY
		CPY	#8
		BCC	@TVS1A
		DEY			; AND THEN
@TVS2:		LDA	TVTYPE,Y	; PUT IN VAR TABLE
		STA	(SVESA),Y	; ENTRY
		DEY
		BPL	@TVS2

@TVSUC:		BIT	TVTYPE		; WAS THERE A PAREN
		BVC	@TVNP		; BR IF NOT
		DEC	TVSCIX		; LET SYNTAX SEE PAREN

@TVNP:		LDA	TVSCIX		; GET NEW CIX
		STA	CIX		; TO CIX

		LDA	STENUM		; GET TABLE ENTRY NO
		BMI	@TVFULL		; BR IF > $7F
		ORA	#$80		; MAKE IT > $7F
		.if	BASIC_REVISION = 1
		JSR	_SETCODE		; SET CODE TO OUTPUT BUFFER
		CLC			; SET SUCCESS CODE
		RTS			; RETURN
		.else
		clc
		jmp	_SETCODE
		.endif

@TVFULL:	jmp	ERRVSF		; GO TO ERROR RTN

; TSTALPH	TEST CIX FOR ALPHA

_TSALPH:	LDY	CIX
		LDA	(INBUFF),Y
TSALPH:		CMP	#'A'
		BCC	_TAFAIL
		CMP	#'Z'+1
		RTS

_TAFAIL:	SEC
		RTS

; _TNCON	EXTERNAL SUBROUTINE TO CHECK FOR NUMBER

_TNCON:		JSR	SKBLANK
		LDA	CIX
		STA	TVSCIX
		JSR	CVAFP		; GO TEST AND CONV
		BCC	@TNC1		; BR IF NUMBER
		LDA	TVSCIX
		STA	CIX
		RTS			; RETURN FAIL

@TNC1:		LDA	#CBCD		; SET NUMERIC CONST
		JSR	_SETCODE

		.if	BASIC_REVISION = 1
		LDY	COX
		.else
		iny
		.endif
		LDX	#0
@TNC2:		LDA	FR0,X		; MOVE CONST TO STMT
		STA	(LOMEM),Y
		INY
		INX
		CPX	#6
		BCC	@TNC2
		STY	COX
		CLC
		RTS

;	EXT SRT TO CHECK FOR STR CONST

_TSCON:		JSR	SKBLANK
		LDY	CIX		; GET INDEX
		LDA	(INBUFF),Y	; GET CHAR
		CMP	#'"'		; IS IT DQUOTE

		.if	BASIC_REVISION = 1
		BEQ	@TSC1		; BR IF DQ
		SEC			; SET FAIL
		RTS			; RETURN
		.else
		bne	_TAFAIL
		.endif

@TSC1:		LDA	#CSTOK		; SET SCON CODE
		JSR	_SETCODE
		LDA	COX		; SET COX
		STA	TSCOX		; SAVE FOR LENGTH
		JSR	_SETCODE	; SET DUMMY FOR NOW

@TSC2:		INC	CIX		; NEXT INPUT CHAR
		LDY	CIX
		LDA	(INBUFF),Y
		CMP	#CR		; IS IT CR
		BEQ	@TSC4		; BR IF CR
		CMP	#'"'		; IS IT DQ
		BEQ	@TSC3		; BR IF DQ
		JSR	_SETCODE	; OUTPUT IT
		JMP	@TSC2		; NEXT

@TSC3:		INC	CIX		; INC CIX OVER DQ
@TSC4:		CLC
		LDA	COX		; LENGTH IS COX MINUS
		SBC	TSCOX		; LENGTH BYTE COX
		LDY	TSCOX
		STA	(LOMEM),Y	; SET LENGTH

_TSSUC:		CLC			; SET SUCCESS
		RTS			; DONE

; Search a Table
;
;		TABLE FORMAT:
;		GARBAGE TO SKIP [N]
;		ASCII CHAR      [N]
;		  WITH LEAST SIGNIFICANT BYTE HAVING
;		  MOST SIGNIFICANT BIT ON
;		LAST TABLE ENTRY MUST HAVE FIRST ASCII
;		  CHAR = 0
;
;		ENTRY PARMS:
;		  X = SKIP LENGTH
;		  A,Y = TABLE ADR [HIGH LOW]
;		  ARGUMENT = INBUFF + CIX
;		EXIT PARMS:
;		  CARRY = CLEAR IF FOUND
;		  X = FOUND ARGUMENT END CIX+1
;		  SRCADR = TABLE ENTRY ADR
;		  STENUM = TABLE ENTRY NUMBER
;
SEARCH:		STX	SRCSKP		; SAVE SKIP FACTOR
		LDX	#$FF		; SET ENTRY NUMBER
		STX	STENUM		; TO ZERO

_SRC1:		STA	SRCADR+1	; SET SEARCH ADR
		STY	SRCADR
		INC	STENUM		; INC ENTRY NUMBER
		LDX	CIX		; GET ARG DISPL
		LDY	SRCSKP		; GET SKIP LENGTH
		LDA	(SRCADR),Y	; GET FIRST CHAR
		BEQ	_SRCNF		; BR IF EOT
		LDA	#0		; SET STATUS = EQ
		PHP			; AND PUSH IT

_SRC2:		LDA	LBUFF,X		; GET INPUT CHAR
		AND	#$7F		; TURN OFF MSB
		CMP	#'.'		; IF WILD CARD
		BEQ	_SRC5		; THEN BR
_SRC2A:		EOR	(SRCADR),Y	; EX-OR WITH TABLE CHAR
		ASL			; SHIFT MSB TO CARRY
		BEQ	_SRC3		; BR IF [ARG=TAB] CHAR

		PLA			; POP STATUS
		PHP			; PUSH NEW STATUS

_SRC3:		INY			;INC TABLE INDEX
		INX			;INC ARG INDEX
		BCC	_SRC2		; IF TABLE MSB OFF, CONTINUE
					;ELSE END OF ENTRY
		PLP			;GET STATUS
		.if	BASIC_REVISION = 1
		BEQ	_SRCFND		;BR IF NO MIS MATCH
		.else
		beq	_TSSUC
		.endif

SRCNXT:		CLC
		TYA			;ACV=ENTRY LENGTH
		ADC	SRCADR		;PLUS START ADR [L]
		TAY			;TO Y
		LDA	SRCADR+1	;ETC
		ADC	#0
		BNE	_SRC1		;BR ALLWAYS

_SRCFND:	.if	BASIC_REVISION = 1
		CLC			; INDICATE FOUND
		RTS
		.endif

_SRCNF:		SEC			; INDICATE NOT FOUND
		RTS

_SRC5:		LDA	#2		; IF NOT
		CMP	SRCSKP		; STMT NAME TABLE
		BNE	_SRC2A		; THEN IGNORE
@SRC6:		LDA	(SRCADR),Y	;TEST MSB OF TABLE
		BMI	@SRC7		; IF ON DONE
		INY			; ELSE
		BNE	@SRC6		; LOOK AT NEXT CHAR
@SRC7:		SEC			; INDICATE MSB ON
		BCS	_SRC3		; AND RE-ENTER CODE

; Statement Name Table

;
; SNTAB- STATEMENT NAME TABLE
;	EACH ENTRY HAS SYNTAX TBLE ADR PTR
;	FOLLOWED BY STMT NAME
;
SNTAB:		WordBasicString _SREM,"REM"
		WordBasicString _SDATA,"DATA"
		WordBasicString _SINPUT,"INPUT"
		WordBasicString _SCOLOR,"COLOR"
		WordBasicString _SLIST,"LIST"
		WordBasicString _SENTER,"ENTER"
		WordBasicString _SLET,"LET"
		WordBasicString _SIF,"IF"
		WordBasicString _SFOR,"FOR"
		WordBasicString _SNEXT,"NEXT"
		WordBasicString _SGOTO,"GOTO"
		WordBasicString _SGOTO,"GO TO"
		WordBasicString _SGOSUB,"GOSUB"
		WordBasicString _STRAP,"TRAP"
		WordBasicString _SBYE,"BYE"
		WordBasicString _SCONT,"CONT"
		WordBasicString _SCOM,"COM"
		WordBasicString _SCLOSE,"CLOSE"
		WordBasicString _SCLR,"CLR"
		WordBasicString _SDEG,"DEG"
		WordBasicString _SDIM,"DIM"
		WordBasicString _SEND,"END"
		WordBasicString _SNEW,"NEW"
		WordBasicString _SOPEN,"OPEN"
		WordBasicString _SLOAD,"LOAD"
		WordBasicString _SSAVE,"SAVE"
		WordBasicString _SSTATUS,"STATUS"
		WordBasicString _SNOTE,"NOTE"
		WordBasicString _SPOINT,"POINT"
		WordBasicString _SXIO,"XIO"
		WordBasicString _SON,"ON"
		WordBasicString _SPOKE,"POKE"
		WordBasicString _SPRINT,"PRINT"
		WordBasicString _SRAD,"RAD"
		WordBasicString _SREAD,"READ"
		WordBasicString _SREST,"RESTORE"
		WordBasicString _SRET,"RETURN"
		WordBasicString _SRUN,"RUN"
		WordBasicString _SSTOP,"STOP"
		WordBasicString _SPOP,"POP"
		WordBasicString _SPRINT,"?"
		WordBasicString _SGET,"GET"
		WordBasicString _SPUT,"PUT"
		WordBasicString _SGR,"GRAPHICS"
		WordBasicString _SPLOT,"PLOT"
		WordBasicString _SPOS,"POSITION"
		WordBasicString _SDOS,"DOS"
		WordBasicString _SDRAWTO,"DRAWTO"
		WordBasicString _SSETCOLOR,"SETCOLOR"
		WordBasicString _SLOCATE,"LOCATE"
		WordBasicString _SOUND,"SOUND"
		WordBasicString _SLPRINT,"LPRINT"
		WordBasicString _SCSAVE,"CSAVE"
		WordBasicString _SCLOAD,"CLOAD"

		.word	_SILET-1
		.byte	$00,$80		; silent "LET"

		.byte	$00,$2A
		BasicString "ERROR-  "

		.if	BASIC_REVISION > 1
STOPPED_STR:	BasicString "STOPPED "
		.endif

;
; SYNTAX TABLES
;

; Syntax Table OP Codes
; $00 _ANTV	Absolute Non-Terminal Vector (ANTV) to sub-call another rule
; $01 _ESRT	External Subroutine Call (ESRT) to call a handler for more complex rules
; $02 _OR	ABML or
; $03 _RTN	(aka #) Return, marks the end of an ABML rule. Return pass or fail.
; $0D _UNKN	(aka <UNKN>) Not sure what this does in BASIC Rev. B.
; $0E _VEXP	(aka <EXP>) Expression Non-Terminal Vector. Shorthand for ANTV AD(EXP)
; $0F _CHNG	Change Last Token to X. e.g., to rectify '=' as assign or compare.

; Helper to reverse-engineer JS offsets:
; python -c "import sys; print(hex(int(sys.argv[1],0)+(int(sys.argv[2],0) ^ 0x40) - 0x80))" 0xA616 0xD8

.define	JS(adr)	$80 + (((adr - *) & $7F) ^ $40)
.define	AD(adr)	(adr - 1)
.define	CHNG(val) _CHNG, val
.define	UNJS(val) (* + (val ^ $40) - $80)
.define	ANTV(adr) _ANTV, <AD(adr), >AD(adr)
.define	ESRT(adr) _ESRT, <AD(adr), >AD(adr)

; <EXP> = (<EXP>)<NOP> | <UNARY><EXP> | <NV><NOP>#

_EXP:		.if	BASIC_REVISION = 1
		.byte	CLPRN,JS(_EXP),CRPRN,JS(_NOP),_OR,JS(_UNARY),JS(_EXP),_OR
		.else
		.byte	JS(_UNARY),JS(_EXP2),_OR,JS(_EXP2),_RTN
_EXP2:		.byte	CLPRN,JS(_SFUN),CRPRN,JS(_NOP),_OR
		.endif
		.byte	JS(_NV),JS(_NOP),_RTN

; <UNARY> = + | - | NOT#

_UNARY:		.byte	CPLUS,CHNG(CUPLUS),_OR,CMINUS,CHNG(CUMINUS),_OR,CNOT,_RTN

; <NV> = <NFUN> | <NVAR> | <NCON> | <STCOMP>#

_NV:		.byte	JS(_NFUN),_OR,JS(_NVAR),_OR,ESRT(_TNCON),_OR,ANTV(_STCOMP),_RTN

; <NOP> = <OP><EXP> | &#

_NOP:		.byte	JS(_OP),JS(_EXP),_OR,_RTN

; <OP> = ** | + | - | * | / | <= | >= | <> | > | < | = | AND | OR#

_OP:		.byte	CEXP,_OR,CPLUS,_OR,CMINUS,_OR,CMUL,_OR,CDIV,_OR,CLE,_OR,CGE,_OR
		.byte	CNE,_OR,CGT,_OR,CLT,_OR,CEQ,_OR,CAND,_OR,COR,_RTN

; <NVAR> = <TNVAR><NMAT>#

_NVAR:		.byte	ESRT(_TNVAR),JS(_NMAT),_RTN

; <NMAT> = (<EXP><NMAT2>) | &#

_NMAT:		.if	BASIC_REVISION > 1
		.byte	_UNKN
		.endif
		.byte	CLPRN,CHNG(CALPRN),_VEXP,JS(_NMAT2),CRPRN,_OR,_RTN

; <NMAT2> = ,<EXP> | &#

_NMAT2:		.byte	CCOM,CHNG(CACOM),_VEXP,_OR,_RTN

; <NFUN> = <NFNP><NFP> | <NFSP><SFP> | <NFUSR>#

_NFUN:		.byte	CNFNP,JS(_NFP),_OR,ANTV(_NFSP),JS(_SFP),_OR,JS(_NFUSR),_RTN

; <NFUSR> = USR(<PUSR>)#

_NFUSR:		.byte	CUSR,CLPRN,CHNG(CFLPRN),ANTV(_PUSR),CRPRN,_RTN

; <NFP> = (<EXP>)#

_NFP:		.byte	CLPRN,CHNG(CFLPRN),_VEXP,CRPRN,_RTN

; <SFP> = <STR>)#

_SFP:		.byte	CLPRN,CHNG(CFLPRN),JS(_STR),CRPRN,_RTN

; <STCOMP> = <STR><SOP><STR>#

_STCOMP:	.byte	JS(_STR),JS(_SOP),JS(_STR),_RTN

; <STR> = <SFUN> | <SVAR> | <SCON>#

_STR:		.byte	JS(_SFUN),_OR,JS(_SVAR),_OR,ESRT(_TSCON),_RTN

; <SFUN> = SFNP<NFP>#

_SFUN:		.byte	ANTV(_SFNP),JS(_NFP),_RTN

; <SVAR> = <TSVAR><SMAT>#

_SVAR:		.byte	ESRT(_TSVAR),JS(_SMAT),_RTN

; <SMAT> = (<EXP><SMAT2>) | &#

_SMAT:		.byte	CLPRN,CHNG(CSLPRN),_VEXP,JS(_SMAT2),CRPRN,_OR,_RTN

; <SMAT2> = ,<EXP> | &#

_SMAT2:		.byte	CCOM,CHNG(CACOM),_VEXP,_OR,_RTN

; <SOP> = <><#

_SOP:		.byte	CLE,CHNG(CSLE),_OR
		.byte	CNE,CHNG(CSNE),_OR
		.byte	CGE,CHNG(CSGE),_OR
		.byte	CGT,CHNG(CSGT),_OR
		.byte	CLT,CHNG(CSLT),_OR
		.byte	CEQ,CHNG(CSEQ),_RTN

		; PUT statement

; <PUT> = <D1>,<EXP><EOS>#

_SPUT:		.byte	CPND,_VEXP,CCOM

		; COLOR, GOTO, GO TO, GOSUB, TRAP, GRAPHICS statement

_STRAP:
_SGOTO:
_SGOSUB:
_SGR:
_SCOLOR:
_XEOS:		.byte	_VEXP

		; BYE, CONT, CLR, DEG, END, NEW, RAD, RETURN,
		; STOP, POP, DOS, CSAVE, CLOAD statement

_SCSAVE:
_SCLOAD:
_SDOS:
_SCLR:
_SRET:
_SEND:
_SSTOP:
_SPOP:
_SNEW:
_SBYE:
_SCONT:
_SDEG:
_SRAD:		.byte	JS(_EOS),_RTN

		; LET, silent LET statement

; <LET> = <NVAR> = <EXP><EOS> | <SVAR>=<STR><EOS>#

_SLET:
_SILET:		.byte	ANTV(_NVAR),CEQ,CHNG(CAASN),_VEXP,JS(_EOS),_OR
		.byte	JS(_SVAR),CEQ,CHNG(CSASN),ANTV(_STR),JS(_EOS),_RTN

		; FOR statement

; <FOR> = <TNVAR> = <EXP> TO <EXP><FSTEP><EOS>#

_SFOR:		.byte	ESRT(_TNVAR),CEQ,CHNG(CAASN),_VEXP,CTO,_VEXP,JS(_FSTEP),JS(_EOS),_RTN

; <FSTEP> = STEP<EXP> | &

_FSTEP:		.byte	CSTEP,_VEXP,_OR,_RTN

		; LOCATE statement

; <LOCATE> = <EXP>,<EXP>,<TNVAR><EOL>#

_SLOCATE:	.byte	_VEXP,CCOM,_VEXP,CCOM,JS(_SNEXT),_RTN

		; GET statement

; <GET> = <D1>,<TNVAR>#

_SGET:		.byte	JS(_D1),CCOM

		; NEXT statement

; <NEXT> = <TNVAR><EOS>#

_SNEXT:		.byte	ESRT(_TNVAR),JS(_EOS),_RTN

		; RESTORE statement

; <RESTORE> = <EXP><EOS> | <EOS>#

_SREST:		.byte	_VEXP,JS(_EOS),_OR,JS(_EOS),_RTN

		; INPUT statement

; <INPUT> = <OPD><READ>#

_SINPUT:	.byte	JS(_OPD)

		; READ statement

; <READ> = <NSVARL><EOS>#

_SREAD:		.byte	JS(_NSVRL),JS(_EOS),_RTN

; <EOS> = : | CR #

_EOS:		.byte	CEOS,_OR,CCR,_RTN

		; PRINT, ? statement

; <PRINT> = <D1><EOS> | <D1><PR1><EOS>

_SPRINT:	.byte	JS(_D1),JS(_EOS),_OR,JS(_OPD)

		; LPRINT statement

; <LPRINT> = <PR1> <EOS>

_SLPRINT:	.byte	ANTV(_PR1),JS(_EOS),_RTN

; <D1> = <CPND> <EXP> #

_D1:		.byte	CPND,_VEXP,_RTN

; <NSVAR> = <NVAR> | <SVAR> #

_NSVAR:		.byte	ESRT(_TNVAR),_OR,ESRT(_TSVAR),_RTN

; <NSVRL> = <NSVAR> | <NSV2> | <NADA> #   (Rev.1)
; <NSVRL> = <NSVAR> | <NSV2> #            (Rev.2+)

_NSVRL:		.byte	JS(_NSVAR),JS(_NSV2)
		.if	BASIC_REVISION = 1
		.byte	_OR
		.endif
		.byte	_RTN

; <NSV2> = ,<NSVRL> | &#

_NSV2:		.byte	CCOM,JS(_NSVRL),_OR,_RTN

		; XIO statement

; <XIO> = <EXP>,<D2S>,<FS>,<EXP><EOS>#

_SXIO:		.byte	_VEXP,CCOM

		; OPEN statement

; <OPEN> = <D1>,<EXP>,<EXP>,<FS><EOS>#

_SOPEN:		.byte	JS(_D1),CCOM,JS(_TEXP),CCOM,JS(_FS),JS(_EOS),_RTN

		; CLOSE statement

; <CLOSE> = <D1><EOS>#

_SCLOSE:	.byte	JS(_D1),JS(_EOS),_RTN

		; ENTER, LOAD, SAVE statement

; <ENTER> = <FS><EOS>#

_SENTER:
_SLOAD:
_SSAVE:		.byte	JS(_FS),JS(_EOS),_RTN

		; RUN statement

; <RUN> = <FS><EOS2> | <EOS2>#

_SRUN:		.byte	JS(_FS),JS(_EOS),_OR,JS(_EOS),_RTN

; <OPD> = <D1>, | #

_OPD:		.byte	JS(_D1),CCOM,_OR,JS(_D1),CSC,_OR,_RTN

		; LIST statement

; <LIST> = <FS>;<L2> | <L2>#

_SLIST:		.byte	JS(_FS),JS(_EOS),_OR,JS(_FS),CCOM,JS(_LIS),_OR,JS(_LIS),_RTN

; <LIS> = <L1><EOS2>#

_LIS:		.byte	ANTV(_L1),JS(_EOS2),_RTN

		; STATUS statement

; <STATUS> = <STAT><EOS2>#

_SSTATUS:	.byte	JS(_STAT),JS(_EOS2),_RTN

; <STAT> = <D1>,<NVAR>#

_STAT:		.byte	JS(_D1),CCOM,ANTV(_NVAR),_RTN

		; NOTE, POINT statement

; <SNOTE> = <STAT>,<NVAR><EOS2>#

_SNOTE:
_SPOINT:	.byte	JS(_STAT),CCOM,ANTV(_NVAR),JS(_EOS2),_RTN

; <FS> = <STR>

_FS:		.byte	ANTV(_STR),_RTN

; <TEXP> = <EXP>,<EXP>#

_TEXP:		.byte	_VEXP,CCOM,_VEXP,_RTN

		; SOUND statement

; <SOUND> = <EXP>,<EXP>,<EXP>,<EXP><EOS>#

_SOUND:		.byte	_VEXP,CCOM

		; SETCOLOR statement

; <SETCOLOR> = <EXP>,<EXP>,<EXP><EOS>#

_SSETCOLOR:	.byte	_VEXP,CCOM

		; POKE, PLOT, POSITION, DRAWTO statement

; <...> = <EXP>,<EXP><EOS>#

_SPOKE:
_SPLOT:
_SPOS:
_SDRAWTO:	.byte	JS(_TEXP),JS(_EOS2),_RTN

		; COM, DIM statement

; <DIM> = <NSML><EOS>#

_SCOM:
_SDIM:		.byte	JS(_NSML),JS(_EOS2),_RTN

		; ON statement

; <ON> = <EXP><ON1><EXPL><EOS>#
_SON:		.byte	_VEXP,JS(_ON1),JS(_EXPL),JS(_EOS2),_RTN
; <ON1> = GOTO | GOSUB#
_ON1:		.byte	CGTO,_OR,CGS,_RTN
; <EXPL> = <EXP><EXPL1>#
_EXPL:		.byte	_VEXP,JS(_EXPL1),_RTN
; <EXPL1> = ,<EXPL> | &#
_EXPL1:		.byte	CCOM,JS(_EXPL),_OR,_RTN
; <EOS2> = CEOS | CCR#
_EOS2:		.byte	CEOS,_OR,CCR,_RTN
; <NSMAT> = <TNVAR>(<EXP><NMAT2>)
_NSMAT:		.byte	ESRT(_TNVAR)
		.if	BASIC_REVISION > 1
		.byte	_UNKN
		.endif
		.byte	CLPRN,CHNG(CDLPRN),_VEXP,ANTV(_NMAT2),CRPRN,_OR
		.byte	ESRT(_TSVAR),CLPRN,CHNG(CDSLPR),_VEXP,CRPRN,_RTN

; <NSML> = <NSMAT><NSML2> | &#

_NSML:		.byte	JS(_NSMAT),JS(_NSML2),_OR,_RTN

; <NSML2> = ,<NSML> | &#

_NSML2:		.byte	CCOM,JS(_NSML),_OR,_RTN

		; IF statement

; <IF> = <EXP> THEN <IFA><EOS>#

_SIF:		.byte	_VEXP,CTHEN,JS(_IFA),JS(_EOS2),_RTN
; <IFA> = <TNCON> | <EIF>
_IFA:		.byte	ESRT(_TNCON),_OR,ESRT(_EIF)

; <PR1> = <PEL> | <PSL><PR2> | &#
_PR1:		.byte	JS(_PEL),_OR,JS(_PSL),JS(_PR2),_OR,_RTN
; <PR2> = <PEL> | &#
_PR2:		.byte	JS(_PEL),_OR,_RTN
; <PEL> = <PES><PELA>#
_PEL:		.byte	JS(_PES),JS(_PELA),_RTN
; <PES> = <EXP> | <STR>
_PES:		.byte	_VEXP,_OR,ANTV(_STR),_RTN
; <PELA> = <PSL><PEL> | &#
_PELA:		.byte	JS(_PSL),JS(_PR2),_OR,_RTN
; <PSL> = <PS><PSLA>#
_PSL:		.byte	JS(_PS),JS(_PSLA),_RTN
; <PSLA> = <PSL> | &#
_PSLA:		.byte	JS(_PSL),_OR,_RTN
; <PS> = , | ,#
_PS:		.byte	CCOM,_OR,CSC,_RTN
; <L1> = <EXP><L2> | &#
_L1:		.byte	_VEXP,JS(_L2),_OR,_RTN
; <L2> = ,<EXP> | &#
_L2:		.byte	CCOM,_VEXP,_OR,_RTN

		; REM statement

; <REM> = <EREM>

_SREM:		.byte	ESRT(_EREM)

		; DATA statement

; <DATA> = <EDATA>

_SDATA:		.byte	ESRT(_EDATA)

; <NFSP> = ASC | VAL | ADR | LEN#

_NFSP:		.byte	CASC,_OR,CVAL,_OR,CADR,_OR,CLEN,_RTN

; <SFNP> = STR | CHR#

_SFNP:		.byte	CSTR,_OR,CCHR,_RTN

; <PUSR> = <EXP><PUSR1>#

_PUSR:		.byte	_VEXP,JS(_PUSR1),_RTN
; <PUSR1> = ,<PUSR> | &#
_PUSR1:		.byte	CCOM,CHNG(CACOM),JS(_PUSR),_OR,_RTN

;
; OPNTAB - Operator Name Table
;

OPNTAB:		.byte	$02+$80			; 0x10 DOUBLE QUOTE (unused?)
		.byte	$00+$80			; 0x11 DUMMY FOR SOE

		BasicString ","
		BasicString "$"
		BasicString ":"
		BasicString ";"
		.byte	CR			; CARRIAGE RETURN
		BasicString "GOTO"
		BasicString "GOSUB"
		BasicString "TO"
		BasicString "STEP"
		BasicString "THEN"
		BasicString "#"
						; START OF REAL OPS
		BasicString "<="		; CLE
		BasicString "<>"		; CNE
		BasicString ">="		; CGE
		BasicString "<"			; CGT
		BasicString ">"			; CLT
		BasicString "="			; CEQ
		BasicString "^"			; CEXP - UP ARROW FOR EXP
		BasicString "*"			; CMUL
		BasicString "+"			; CPLUS
		BasicString "-"			; CMINUS
		BasicString "/"			; CDIV

		BasicString "NOT"		; CNOT
		BasicString "OR"		; COR
		BasicString "AND"		; CAND
		BasicString "("			; CLPRN
		BasicString ")"			; CRPRN
		BasicString "="			; CAASN
		BasicString "="			; CSASN
		BasicString "<="		; CSLE
		BasicString "<>"		; CSNE
		BasicString ">="		; CSGE
		BasicString "<"			; CSLT
		BasicString ">"			; CSGT
		BasicString "="			; CSEQ
		BasicString "+"			; CUPLUS - UNARY PLUS
		BasicString "-"			; CUMINUS - UNARY MINUS

		BasicString "("			; CSLPRN - STRING LEFT PAREN

		.byte	$80			; CALPRN - ARRAY LEFT PAREN - DOES NOT PRINT
		.byte	$80			; CDLPRN - DIM LEFT PAREN - DOES NOT PRINT
		BasicString "("			; CFLPRN - FUNCTION LEFT PAREN
		BasicString "("			; CDSLPR - STRING LEFT PAREN
		BasicString ","			; CACOM - ARRAY COMMA

						; CNFNP
		BasicString "STR$" 		; CSTR
		BasicString "CHR$" 		; CCHR
		BasicString "USR" 		; CUSR
		BasicString "ASC" 		; CASC
		BasicString "VAL" 		; CVAL
		BasicString "LEN" 		; CLEN
		BasicString "ADR" 		; CADR
		BasicString "ATN" 		; CATN
		BasicString "COS" 		; CCOS
		BasicString "PEEK" 		; CPEEK
		BasicString "SIN" 		; CSIN
		BasicString "RND" 		; CRND
		BasicString "FRE" 		; CFRE
		BasicString "EXP" 		; CEXP
		BasicString "LOG" 		; CLOG
		BasicString "CLOG" 		; CCLOG
		BasicString "SQR" 		; CSQR
		BasicString "SGN" 		; CSGN
		BasicString "ABS" 		; CABS
		BasicString "INT" 		; CINT
		BasicString "PADDLE" 		; CPADDLE
		BasicString "STICK" 		; CSTICK
		BasicString "PTRIG" 		; CPTRIG
		BasicString "STRIG" 		; CSTRIG

		.byte	0

		; END OF OPNTAB & FNTAB

;
; Memory Manager
;

; MEMORY MANAGEMENT CONSISTS OF EXPANDING AND
; CONTRACTING TO INFORMATION AREA POINTED TO
; 8Y THE ZERO PAGE POINTER TABLES. ROUTINES
; MODIFY THE ADDRESS IN THE TABLES AND
; MOVE DATA AS REQUIRED. THE TWO FUNDAMENTAL
; ROUTINES ARE 'EXPAND' AND 'CONTRACT'

; EXPAND
;	X = ZERO PAGE ADDRESS OF TABLE AT WHICH
;	EXPANSION IS TO START
;	Y EXPANSION SIZE IN BYTES [LOW]
;	A EXPANSION SIZE IN BYTES [HIGH]

; EXPLOW - FOR EXPANSION < 256 BYTES
;		SETS A = 0

EXPLOW:		LDA	#0

EXPAND:		STY	ECSIZE			; SAVE EXPAND SIZE
		STA	ECSIZE+1

		.if	BASIC_REVISION > 1
		TYA
		.endif

		SEC

		.if	BASIC_REVISION = 1
		LDA	MEMTOP			; TEST MEMORY TO BE FULL
		ADC	ECSIZE
		TAY				; MEMTOP+ECSIZE+1
		LDA	MEMTOP+1
		.else
		adc	MEMTOP
		tay
		lda	MEMTOP+1
		.endif

		ADC	ECSIZE+1		; MUST BE LE
		CMP	HIMEM+1
		BCC	@EXP2			; HIMEM
		BNE	@EXP1
		CPY	HIMEM
		BCC	@EXP2
		BEQ	@EXP2
@EXP1:		JMP	MEMFULL

@EXP2:		SEC				; FORM MOVE LENGTH [MVLNG]
		LDA	MEMTOP			; MOVE FROM ADR [MVFA]
		SBC	0,X			; MVLNG = MEMTOP-EXPAND ADR
		STA	MVLNG
		LDA	MEMTOP+1		; MVFA[L] EXP ADR [L]
		SBC	1,X
		STA	MVLNG+1			; MVFA[H] EXP ADR[H] + MVLNG[H]

		CLC				; DURING MOVE MVLNG[L]
		ADC	1,X			; WILL BE ADDED SUCH
		STA	MVFA+1			; THAT MVFA = MEMTOP

		LDA	0,X			; SAVE PREMOVE EXPAND AT VALUE
		STA	MVFA			; SET MVFA LOW
		STA	SVESA			; FORM MOVE TO ADR [MVTA]
		ADC	ECSIZE			; MVTA[L] = EXP ADR[L] + ECSIZE[L]

		STA	MVTA			; MVTA[H) = [CARRY + EXP AD-[H]

		LDA	1,X			; +ECSIZE[H]] + MVLNG[H]
		STA	SVESA+1
		ADC	ECSIZE+1		; DURING MOVE MVLNG[L]
		ADC	MVLNG+1			; WILL BE ADDED SUCH THAT
		STA	MVTA+1			; MVTA = MEMTOP + ECSIZE

@EXP3:		LDA	0,X			; ADD ECSIZE TO
		ADC	ECSIZE			; ALL TABLE ENTRIES
		STA	0,X			; FROM EXPAND AT ADR
		LDA	1,X			; TO HIMEM
		ADC	ECSIZE+1
		STA	1,X
		INX
		INX
		CPX	#MEOLFLG
		BCC	@EXP3
		STA	APMH+1			; SET NEW APL
		LDA	MEMTOP			; HI MEM TO
		STA	APMH			; MEMTOP

		LDX	MVLNG+1			; X = MVLNG[H]
		INX				; PLUS ONE
		LDY	MVLNG			; T = MVLNG[H]
		BNE	@EXP6			; TEST ZERO LENGTH

		.if	BASIC_REVISION = 1
		BEQ	@EXP7			; BR IF LOW = 0
		.elseif	BASIC_REVISION = 2
		dex
		bne	@EXP6
		rts
		.else
		nop
		beq	@EXP7			; BR IF LOW = 0
		nop
		.endif

@EXP4:		DEY				; DEC MVLNG[L]
		DEC	MVFA+1			; DEC MVFA[H]
		DEC	MVTA+1			; DEC MVTA[H]

@EXP5:		LDA	(MVFA),Y		; MVFA BYTE
		STA	(MVTA),Y		; TO MVTA
@EXP6:		DEY				; DEC COUNT LOW
		BNE	@EXP5			; BR IF NOT ZERO

		LDA	(MVFA),Y		; MOVE THE ZERO BYTE
		STA	(MVTA),Y

@EXP7:		DEX				; IF MVLNG[H] IS NOT
		BNE	@EXP4			; ZERO THEN MOVE 256 MORE
						; ELSE
		RTS				; DONE

; CONTRACT
;	X ZERO PAGE ADR OF TABLE AT WHICH
;		CONTRACTION WILL START
;	Y CONTRACT SIZE IN BYTES [LOW]
;	A CONTRACT SIZE IN BYTES [HI]
; CONTLOW
;	SETS A = 0
;
CONTLOW:	.if	BASIC_REVISION > 1
		tay
		.endif
CONTLOW1:	LDA	#0
CONTRACT:	STY	ECSIZE			; SAVE CONTRACT SIZE
		STA	ECSIZE+1

		SEC				; FORM MOVE LENGTH [LOW]
		LDA	MEMTOP
		SBC	0,X			; MVLNG[L] = $100-
		EOR	#$FF			; [MEMTOP[L]] - CON AT VALUE [L]
		TAY				; THIS MAKES START Y AT
		INY				; MOVE HAVE A 2'S COMPLEMENT
		STY	MVLNG			; REMAINDER IN IT

		LDA	MEMTOP+1		; FORM MOVE LENGTH[HIGH]
		SBC	1,X
		STA	MVLNG+1

		LDA	0,X			; FORM MOVE FROM ADR [MVFA]
		SBC	MVLNG			; MVFA = CON AT VALUE
		STA	MVFA			; MINUS MVLNG[L]
		LDA	1,X			; DURING MOVE MVLNG[L]
		SBC	#0			; WILL BE ADDED BACK INTO
		STA	MVFA+1			; MVFA IN [IND],Y INST

		STX	MVTA			; TEMP SAVE OF CON AT DISPL

@CONT1:		SEC				; SUBTRACT ECSIZE FROM
		LDA	0,X			; ALL TABLE ENTRY FROM
		SBC	ECSIZE			; CON AT ADR TO HIMEM
		STA	0,X
		LDA	1,X
		SBC	ECSIZE+1
		STA	1,X
		INX
		INX
		CPX	#MEMTOP+2
		BCC	@CONT1
		STA	APMH+1			; SET NEW APL
		LDA	MEMTOP			; HI MEM TO
		STA	APMH			; MEMTOP

		LDX	MVTA

		LDA	0,X			;FORM MOVE TO ADDR [MVTA]
		SBC	MVLNG			; MVTA = NEW CON AT VALUE
		STA	MVTA			; MINUS MVLNG [L]
		LDA	1,X			; DURING MOVE MVLNG[L]
		SBC	#0			; WILL BE ADDED BACK INTO
		STA	MVTA+1			; MVTA IN [INO],Y INST

FMOVER:		LDX	MVLNG+1			; GET MOVE LENGTH HIGH
		INX				; INC SO MOVE CAN BNE
		LDY	MVLNG			; GET MOVE LENGTH LOW
		BNE	@CONT2			; IF NOT ZERO GO

		.if	BASIC_REVISION = 1
		BEQ	@CONT4			; BR IF LOW = 0
		.else
		dex
		.if	BASIC_REVISION > 1
		bne	@CONT2
		.endif
		rts
		.endif

@CONT3:		INC	MVFA+1			;INC MVFA[H]
		INC	MVTA+1			; INC MVTA[H]

@CONT2:		LDA	(MVFA),Y		; GET MOVE FROM BYTE
		STA	(MVTA),Y		; GET MOVE TO BYTE
		INY				; INCREMENT COUNT LOW
		BNE	@CONT2			; BR IF NOT ZERO

@CONT4:		DEX				; DECREMENT COUNT HIGH
		BNE	@CONT3			;BR IF NOT ZERO
		RTS				; ELSE DONE

;
; Execute Control
;

; EXECNL - Execute Next Line

EXECNL:		JSR	SETLN1			; SET UP LIN & NXT STMT

; EXECNS - Execute Next Statement

EXECNS:		JSR	TSTBRK			; TEST BREAK

		.if	BASIC_REVISION = 1
		BNE	@EXBRK			; BR IF BREAK
		.else
		beq	@EXBRK			; BR IF BREAK
		.endif

		LDY	NXTSTD			;GET PTR TO NEXT STMT L
		CPY	MAXCIX			;AT END OF LINE
		BCS	@EXEOL			; BR IF EOL
		LDA	(STMCUR),Y		;GET NEW STMT LENGTH
		STA	NXTSTD			;SAVE AS FUTURE STMT LENGTH
		TYA				;Y=DISPL TO THIS STMT LENGTH
		INY				; PLUS 1 IS DISPL TO CODE
		LDA	(STMCUR),Y		;GET CODE
		INY				;INC TO STMT MEAT
		STY	STINDEX			;SET WORK INDEX

		JSR	@STGO			;GO EXECUTE

		.if	BASIC_REVISION > 1
		nop
		.endif

		JMP	EXECNS			;THEN DO NEXT STMT

@STGO:		ASL				;TOKEN*2
		TAX
		LDA	STETAB,X		; GET ADR AND
		PHA				;PUSH TO STACK
		LDA	STETAB+1,X		; AND GO TO
		PHA				;VIA
		RTS				;RTS

@EXEOL:		LDY	#1
		LDA	(STMCUR),Y
		BMI	@EXFD			; BR IF DIR

		LDA	MAXCIX			;GET LINE LENGTH
		JSR	GNXTL			;INC STMCUR
		JSR	TENDST			;TEST END STMT TABLE
		BPL	EXECNL			;BR NOT END

@EXDONE:	JMP	XEND			; GO BACK TO SYNTAX
@EXBRK:		JMP	XSTOP			; BREAK, DO STOP
@EXFD:		JMP	SNX3			; GO TO SYNTAX VIA READY MSG

; GETSTMT - Get Statement in Statement Table
;	SEARCH FOR STMT THAT HAS TSLNUM
;	SET STMCUR TO POINT TO IT IF FOUND
;	OR TO WHERE IT WOULD GO IF NOT FOUND
;	CARRY SET IF NOT FOUND
GETSTMT:
;	
;	SAVE CURRENT LINE ADDR
;
		LDA	STMCUR
		STA	SAVCUR
		LDA	STMCUR+1
		STA	SAVCUR+1
		LDA	STMTAB+1		;START AT TOP OF TABLE
		LDY	STMTAB

		sta	STMCUR+1		;SET STMCUR
		sty	STMCUR

@GS2:		LDY	#1
		LDA	(STMCUR),Y		;GET STMT LNO [HI]
		CMP	TSLNUM+1		;TEST WITH TSLNUM
		BCC	@GS3			;BR IF S<TS
		BNE	@GSRT1			;BR IF S>TS
		DEY				;S=TS, TEST LOW BYTE
		LDA	(STMCUR),Y
		CMP	TSLNUM
		BCC	@GS3			;BR S<TS
		BNE	@GSRT1			;BR S>TS
		CLC				;S=TS, CLEAR CARY
@GSRT1:		RTS				;AND RETURN [FOUND]

@GS3:		JSR	GETLL			;GO GET THIS GUYS LENGTH
		JSR	GNXTL
		JMP	@GS2

GNXTL:		CLC
		ADC	STMCUR			;ADD LENGTH TO STMCUR
		STA	STMCUR
		.if	BASIC_REVISION = 1
		TAY
		.endif
		LDA	STMCUR+1
		ADC	#0
		STA	STMCUR+1
		RTS

GETLL:		LDY	#2
		LDA	(STMCUR),Y
		RTS

; TENDST - Test End of Statement Table

TENDST:		LDY	#1
		LDA	(STMCUR),Y

		.if	BASIC_REVISION = 1
		RTS
		.endif

		; Execute REM, DATA

XREM:
XDATA:
TESTRTS:	RTS

		; Execute BYE

XBYE:		JSR	CLSALL
		JMP	SELFSV

		; Execute DOS

XDOS:		JSR	CLSALL
		JMP	(DOSVEC)

TSTBRK:		.if	BASIC_REVISION = 1
		LDY	#0

		LDA	BRKBYT		; LOAD BREAK BYTE
		BNE	@TB2
		LDY	#$FF
		STY	BRKBYT
		.else
		ldy	BRKBYT
		bne	@TBX
		dec	BRKBYT
		.endif
@TB2:		TYA			; SET COND DONE
@TBX:		RTS			; DONE

;
; Statement Execution Table
;

;	STETAB	- STATEMENT EXECUTION TABLE
;		- CONTAINS STMT EXECUTION ADR
;		- MUST BE IN SAME ORDER AS SNTAB

STETAB:		.dbyt	XREM-1,XDATA-1,XINPUT-1,XCOLOR-1,XLIST-1,XENTER-1,XLET-1,XIF-1
		.dbyt	XFOR-1,XNEXT-1,XGOTO-1,XGOTO-1,XGOSUB-1,XTRAP-1,XBYE-1,XCONT-1
		.dbyt	XCOM-1,XCLOSE-1,XCLR-1,XDEG-1,XDIM-1,XEND-1,XNEW-1,XOPEN-1
		.dbyt	XLOAD-1,XSAVE-1,XSTATUS-1,XNOTE-1,XPOINT-1,XXIO-1,XON-1,XPOKE-1
		.dbyt	XPRINT-1,XRAD-1,XREAD-1,XREST-1,XRTN-1,XRUN-1,XSTOP-1,XPOP-1
		.dbyt	XPRINT-1,XGET-1,XPUT-1,XGR-1,XPLOT-1,XPOS-1,XDOS-1,XDRAWTO-1
		.dbyt	XSETCOLOR-1,XLOCATE-1,XSOUND-1,XLPRINT-1,XCSAVE-1,XCLOAD-1,XLET-1,XERR-1

;
; Operator Execution Table
;

;	OPETAB	- OPERATOR EXECUTION TABLE
;		- CONTAINS OPERATOR EXECUTION ADR
;		- MUST BE IN SAME ORDER AS OPNTAB

OPETAB:		.dbyt	XPLE-1,XPNE-1,XPGE-1,XPLT-1,XPGT-1,XPEQ-1,XPPOWER-1,XPMUL-1
		.dbyt	XPPLUS-1,XPMINUS-1,XPDIV-1,XPNOT-1,XPOR-1,XPAND-1,XPLPRN-1,XPRPRN-1
		.dbyt	XPAASN-1,XSAASN-1,XPSLE-1,XPSNE-1,XPSGE-1,XPSLT-1,XPSGT-1,XPEQ-1
		.dbyt	XPUPLUS-1,XPUMINUS-1,XPSLPRN-1,XPALPRN-1,XPDLPRN-1,XPFLPRN-1,XDPSLP-1,XPACOM-1
		.dbyt	XPSTR-1,XPCHR-1,XPUSR-1,XPASC-1,XPVAL-1,XPLEN-1,XPADR-1,XPATN-1
		.dbyt	XPCOS-1,XPPEEK-1,XPSIN-1,XPRND-1,XPFRE-1,XPEXP-1,XPLOG-1,XPL10-1
		.dbyt	XPSQR-1,XPSGN-1,XPABS-1,XPINT-1,XPPDL-1,XPSTICK-1,XPPTRIG-1,XPSTRIG-1
;
; Execute Expression
;

		; Execute LET
XLET:
EXEXPR:
		JSR	EXPINT			; GO INIT

_EXNXT:		JSR	_EGTOKEN		; GO GET TOKEN
		BCS	@EXOT			; BR IF OPERATOR

		JSR	ARGPUSH			; PUSH ARG

		.if	BASIC_REVISION = 1
		JMP	_EXNXT			; GO FOR NEXT TOKEN
		.else
		bmi	_EXNXT
		.endif

@EXOT:		STA	EXSVOP			; SAVE OPERATOR
		TAX
		LDA	OPRTAB-16,X		; GET OP PREC
		LSR
		LSR
		LSR
		LSR
		STA	EXSVPR			; SAVE GOES ON PREC

_EXPTST:	LDY	OPSTKX			; GET OP STACK INDEX
		LDA	(ARGSTK),Y		; GET TOP OP
		TAX
		LDA	OPRTAB-16,X		; GET TOP OP PREC
		AND	#$0F
		CMP	EXSVPR			; [TOP OP]: [NEW OP]
		BCC	_EOPUSH			; IF T<N, PUSH NEW
						;	ELSE POP
		TAX				; IF POP SOE
		BEQ	_EXEND			; THEN DONE

_EXOPOP:	LDA	(ARGSTK),Y		; RE-GET TOS OP
		INC	OPSTKX			; DEC OP STACK INDEX
		JSR	_EXOP			; GET EXECUTE OP
		JMP	_EXPTST			; GO TEST OP WITH NEW TOS

_EOPUSH:	LDA	EXSVOP			; GET OP TO PUSH
		DEY				; DEC TO NEXT ENTRY
		STA	(ARGSTK),Y		; SET OP IN STACK
		STY	OPSTKX			; SAVE NEW OP STACK INDEX
		JMP	_EXNXT			; GO GET NEXT TOKEN

		.if	BASIC_REVISION = 1
_EXEND:
XPLPRN:		RTS				; DONE EXECUTE EXPR
		.endif

_EXOP:		SEC				; SUBTRACT FOR REL 0
		SBC	#CSROP			; VALUE OF FIRST REAL OP
		ASL				; VALUE * 2
		TAX
		LDA	OPETAB,X		; PUT OP EXECUTION
		PHA				; ROUTINE ON STACK
		LDA	OPETAB+1,X		; AND GOTO
		PHA				; VIA
		RTS				; RTS

;
; Initialize Expression Parameters
;

EXPINT:		LDY	#$FF
		LDA	#CSOE			; OPERATOR
		STA	(ARGSTK),Y		; STACK
		STY	OPSTKX
		INY				; AND INITIALIZE
		STY	COMCNT
		STY	ARSTKX			; ARG STACK
		STY	ADFLAG			; ASSIGN FLAG

		.if	BASIC_REVISION > 1
_EXEND:
XPLPRN:
; Unary plus
XPUPLUS:
		.endif

		RTS

;
; GETTOK - Get Next Token and Classify
;
GETTOK:
_EGTOKEN:	LDY	STINDEX			; GET STMT INDEX
		INC	STINDEX			; INC TO NEXT
		LDA	(STMCUR),Y		; GET TOKEN
		BMI	_EGTVAR			; BR IF VAR

		CMP	#$0F			; TOKEN: $0F
		BCC	@EGNC			; BR IF $0E, NUMERIC CONST
		BEQ	_EGSC			; BR IF $0F, STR CONST
		RTS				; RTN IF OPERATOR

@EGNC:

NCTOFR0:	LDX	#0
@EGT1:		INY				; INC LINE INDEX
		LDA	(STMCUR),Y		; GET VALUE FROM STMT TBL
		STA	FR0,X			; AND PUT INTO FR0
		INX
		CPX	#6
		BCC	@EGT1

		INY				; INY Y BEYOND CONST
		LDA	#EVSCALER		; ACU=SCALER
		TAX				; X = VAL NO 0
		BEQ	_EGST			; GO SET REM

_EGSC:		INY				; INC Y TO LENGTH BYTE
		LDA	(STMCUR),Y		; GET LENGTH
		LDX	#STMCUR			; POINT TO STMCUR
RISC:		STA	VTYPE+EVSLEN		; SET AS LENGTH
		STA	VTYPE+EVSDIM		; AND DIM
		INY
		TYA				; ACU=DISPL TO STR
		CLC
		ADC	$0,X			; DISPL PLUS ADR
		STA	VTYPE+EVSADR		; IS STR ADR
		LDA	#0			; SET = 0
		STA	VTYPE+EVSLEN+1		; LENGTH HIGH
		STA	VTYPE+EVSDIM+1		; DIM HIGH
		ADC	$1,X			; FINISH ADR
		STA	VTYPE+EVSADR+1
		TYA				; ACU=DISPL TO STR
		ADC	VTYPE+EVSLEN		; PLUS STR LENGTH
		TAY				; IS NEW INDEX
		LDX	#0			; VAR NO = 0
		LDA	#EVSTR+EVSDTA+EVDIM	; TYPE = STR
_EGST:		STA	VTYPE			; SET TYPE
		STX	VNUM			; SET NUM
		STY	STINDEX			; SET NEW INDEX
		CLC				; INDICATE VALUE
		RTS				; RETURN

GETVAR:
_EGTVAR:	JSR	GVVTADR			; GET VVT ADR
@EGT2:		LDA	(WVVTPT),Y		; MOVE VVT ENTRY
		STA	VTYPE,Y			; TO FR0
		INY
		CPY	#8
		BCC	@EGT2
		CLC				; INDICATE VALUE
		RTS				; RETURN

AAPSTR:		JSR	ARGPOP

;
; GSTRAD -- Get String [ABS] Address
;
GSTRAD:		LDA	#EVSDTA			; LOAD TRANSFORMED BIT
		BIT	VTYPE			; TEST STRING ADR TRANSFORM
		BNE	@GSARTS			; BR IF ALREADY TRANSFORMED
		ORA	VTYPE			; TURN ON TRANS BIT
		STA	VTYPE			; AND SET
		ROR				; SHIFT DIM BIT TO CARRY
		BCC	@1

		CLC
		LDA	VTYPE+EVSADR		; STRING ADR = STRING DISPL + STARP
		ADC	STARP
		STA	VTYPE+EVSADR
		TAY
		LDA	VTYPE+EVSADR+1
		ADC	STARP+1
		STA	VTYPE+EVSADR+1
@GSARTS:	RTS
@1:		JSR	ERRDIM

ARGPUSH:	INC	ARSLVL			; INC ARG STK LEVEL
		LDA	ARSLVL			; ACU = ARG STACK LEVEL
		ASL				; TIMES 8
		ASL
		ASL
		CMP	OPSTKX			; TEXT EXCEED MAX
		BCS	_APERR			; BR IF GT MAX
		TAY				; Y = NEXT ENTRY ADR
		DEY				; MINUS ONE
		LDX	#7			; X = 7 FOR 8

@APH1:		LDA	VTYPE,X			; MOVE FR0
		STA	(LOMEM),Y		; TO ARGOPS
		DEY				; BACKWARDS
		DEX
		BPL	@APH1
_APRTS:		RTS				; DONE

_APERR:		JMP	ERRAOS			; STACK OVERFLOW

;
; GETPINT -- Get Positive Integer from Expression
;
GETPINT:	JSR	GETINT			; GO GET INT
		LDA	FR0+1			; GET HIGH BYTE

		.if	BASIC_REVISION = 1
		BMI	@GPIERR			; BR > 32767
		RTS				; DONE
@GPIERR:	JMP	ERRLN
		.else
		bpl	_APRTS			; BR < 32768 DONE
		jmp	ERRLN			; JMP > 32767
		.endif

;
; GETINT -- Get Integer from Expression
;
GETINT:		JSR	XLET			; EVAL EXPR
GTINTO:		JSR	ARGPOP			; POP VALUE TO FR0
		JMP	CVFPI			; GO CONVERT FR0 TO INT & RETURN

;
; GET1INT - Get One-Byte Integer from Expression
;
GET1INT:	JSR	GETPINT			; GET INT <32768
		BNE	@ERV1			; IF NOT 1 BYTE, THEN ERROR
		RTS
@ERV1:		JSR	ERVAL

;
; ARGPOP -- Pop Argument Stack Entry to FR0 or FR1
;
ARGPOP:		LDA	ARSLVL			; GET ARG STACK LEVEL
		DEC	ARSLVL			; DEC AS LEVEL
		ASL				; AS LEVEL * 8
		ASL
		ASL
		TAY				; Y = START OF NEXT ENTRY
		DEY				; MINUS ONE
		LDX	#7			; X = 7 FOR 8

@APOP0:		LDA	(ARGOPS),Y		; MOVE ARG ENTRY
		STA	VTYPE,X
		DEY				; BACKWARDS
		DEX
		BPL	@APOP0
		RTS				; DONE

;
; ARGP2 -- Pop TOS to FR1, TOS-1 to FR0
;
ARGP2:		JSR	ARGPOP
		JSR	MV0TO1
		JMP	ARGPOP

;
; POP1 -- Get a Value in FR0
;
;	- EVALUATE EXPRESSION IN STMT LINE &
;	  POP IT INTO FR0
;
POP1:		JSR	EXEXPR			; EVALUATE EXPRESSION

		.if	BASIC_REVISION = 1
		JSR	ARGPOP			; PUSH INTO FR0
		RTS
		.else
		jmp	ARGPOP
		.endif

;
; RTNVAR -- Return Variable to Variable Value Table from FR0
;
RTNVAR:		LDA	VNUM			; GET VAR NUMBER
		JSR	GVVTADR
		LDX	#0

@RV1:		LDA	VTYPE,X			; MOVE FR0 TO
		STA	(WVVTPT),Y		; VAR VALUE TABLE
		INY
		INX
		CPX	#8
		BCC	@RV1
		RTS				; DONE

; Get Value's Value Table Entry Address

GVVTADR:	LDY	#0			; CLEAR ADR HI
		STY	WVVTPT+1
		ASL				; MULT VAR NO
		ASL				; BY 8
		ROL	WVVTPT+1
		ASL
		ROL	WVVTPT+1
		CLC				; THEN
		ADC	VVTP			; ADD VVTP VALIE
		STA	WVVTPT			; TO FORM ENTRY
		LDA	VVTP+1			; ADR
		ADC	WVVTPT+1
		STA	WVVTPT+1
		RTS

;
; Operator Precedence Table
;

OPRTAB:		.byte	$00	; CDQ
		.byte	$00	; CSOE
		.byte	$00	; CCOM
		.byte	$00	; CDOL
		.byte	$00	; CEOS
		.byte	$00	; CSC
		.byte	$00	; CCR
		.byte	$00	; CGTO
		.byte	$00	; CGS
		.byte	$00	; CTO
		.byte	$00	; CSTEP
		.byte	$00	; CTHEN
		.byte	$00	; CPND
		.byte	$88	; CLE
		.byte	$88	; CNE
		.byte	$88	; CGE
		.byte	$88	; CGT
		.byte	$88	; CLT
		.byte	$88	; CEQ
		.byte	$CC	; CEXP
		.byte	$AA	; CMUL
		.byte	$99	; CPLUS
		.byte	$99	; CMINUS
		.byte	$AA	; CDIV
		.if	BASIC_REVISION = 1
		.byte	$77	; CNOT
		.else
		.byte	$DD	; CNOT
		.endif
		.byte	$55	; COR
		.byte	$66	; CAND
		.byte	$F2	; CLPRN
		.byte	$4E	; CRPRN
		.byte	$F1	; CAASN
		.byte	$F1	; CSASN
		.byte	$EE	; CSLE
		.byte	$EE	; CSNE
		.byte	$EE	; CSGE
		.byte	$EE	; CSGT
		.byte	$EE	; CSLT
		.byte	$EE	; CSEQ
		.byte	$DD	; CUPLUS
		.byte	$DD	; CUMINUS
		.byte	$F2	; CSLPRN
		.byte	$F2	; CALPRN
		.byte	$F2	; CDLPRN
		.byte	$F2	; CFLPRN
		.byte	$F2	; CDSLPR
		.byte	$43	; CACOM

				; FUNCTIONS
		.byte	$F2,$F2,$F2,$F2,$F2,$F2,$F2,$F2
		.byte	$F2,$F2,$F2,$F2,$F2,$F2,$F2,$F2
		.byte	$F2,$F2,$F2,$F2,$F2,$F2,$F2,$F2

;
; Miscellaneous Operators
;

; Miscellaneous Operators' Executors

		.if	BASIC_REVISION = 1
; Math Operator +
XPPLUS:		JSR	ARGP2
		JSR	FRADD
		JMP	ARGPUSH
		.endif

; Math Operator -
XPMINUS:	JSR	ARGP2
		JSR	FRSUB
		JMP	ARGPUSH
; Operator *
XPMUL:		JSR	ARGP2
		JSR	FRMUL
		JMP	ARGPUSH
; Operator /
XPDIV:		JSR	ARGP2
		JSR	FRDIV
		JMP	ARGPUSH
; Unary minus
XPUMINUS:	JSR	ARGPOP

		LDA	FR0

		.if	BASIC_REVISION > 1
		beq	@XPM1			; Avoid Negative Zero
		.endif

		EOR	#$80
		STA	FR0
@XPM1:		JMP	ARGPUSH

		.if	BASIC_REVISION = 1
; Unary plus
XPUPLUS:	RTS
		.endif

; Comparison Operator <=
XPLE:
XPSLE:		JSR	XCMP
		BMI	XTRUE
		BEQ	XTRUE
		BPL	XFALSE

; Comparison Operator <>
XPNE:
XPSNE:		JSR	XCMP
		.if	BASIC_REVISION = 1
		BEQ	XFALSE
		BNE	XTRUE
		.else
		jmp	_TFNEAR
		.endif

; Comparison Operator <
XPLT:
XPSLT:		JSR	XCMP
		BMI	XTRUE
		BPL	XFALSE

; Comparison Operator >
XPGT:
XPSGT:		JSR	XCMP
		BMI	XFALSE
		BEQ	XFALSE
		BPL	XTRUE

; Comparison Operator >=
XPGE:
XPSGE:		JSR	XCMP
		BMI	XFALSE
		BPL	XTRUE

; Comparison Operator =
XPEQ:		JSR	XCMP
		.if	BASIC_REVISION = 1
		BEQ	XTRUE
		BNE	XFALSE
		.else
		jmp	_TFNEAR2
		.endif

; Logical AND
XPAND:		JSR	ARGP2
		LDA	FR0
		AND	FR1

		.if	BASIC_REVISION = 1
		BEQ	XFALSE
		BNE	XTRUE
		.else
		jmp	_TFNEAR
		.endif

; Logical OR
XPOR:		JSR	ARGP2
		LDA	FR0
		ORA	FR1

		; 0 FALSE, else TRUE
_TFNEAR:	BEQ	XFALSE
		BNE	XTRUE

; Logical NOT
XPNOT:		JSR	ARGPOP
		LDA	FR0

		; 0 FALSE, else TRUE
_TFNEAR2:	BEQ	XTRUE
XFALSE:		LDA	#0
		TAY
		BEQ	XTF

XTRUE:		LDA	#$40

XTI:		LDY	#1

XTF:		STA	FR0
		STY	FR0+1
		LDX	#$D6
		LDY	#4
		JSR	__DA48
		STA	$D2

XPUSH:		JMP	ARGPUSH


; XPSGN -- Sign Function

XPSGN:		JSR	ARGPOP
		LDA	FR0
		BEQ	XPUSH
		BPL	XTRUE
		LDA	#$C0			; GET MINUS EXPONENT
		BMI	XTI

; XCMP -- Compare Executor

XCMP:		LDY	OPSTKX			; GET OPERATOR THAT
		DEY				; GOT US HERE
		LDA	(LOMEM),Y
		CMP	#CSLE			; IF OP WAS ARITHMETIC
		BCC	FRCMPP			; THEN DO FP REG COMP
		JMP	STRCMP			; ELSE DO STRING COMPARE

FRCMPP:		JSR	ARGP2

;
; FRCMP -- Compare Two Floating Point Numbers
;
;	ON ENTRY	FR0 & FR1 CONTAIN FLOATING POINT #'S
;
;	ON EXIT		CC = + FRO > FR1
;			CC = - FR0 < FR1
;			CC = 0 FRE0 = FR1
;
FRCMP:		JSR	FRSUB			; SUBTRACT FR1 FROM FR0
		LDA	FR0			; GET FR0 EXPONENT
		RTS				; RETURN WITH CC SET

;
; FRADD -- Floating Point Add
;	DOES NOT RETURN IF ERROR
;
FRADD:		JSR	FADD			; ADD TWO #
		BCS	_ERROV			; BR IF ERROR
		RTS

;
; FRSUB -- Floating Point Subtract
;	DOES NOT RETURN IF ERROR
;
FRSUB:		JSR	FSUB			; SUB TWO #
		BCS	_ERROV
		RTS

;
; FRMUL -- Floating Point Multiply
;	DOES NOT RETURN IF ERROR
;
FRMUL:		JSR	FMUL
		BCS	_ERROV
		RTS

;
; FRDIV -- Floating Point Divide
;	DOES NOT RETURN IF ERROR
;
FRDIV:		JSR	FDIV			; DIVIDE TWO #
		BCS	_ERROV			; BR IF ERROR
		RTS

_ERROV:		JSR	EROVFL

;
; CVFPI -- Convert Floating Point to Integer
;	DOES NOT RETURN IF ERROR
;
CVFPI:		JSR	FPI			; GO CONVERT TO INTEGER
		BCS	@ERRVAL			; IF ERROR, BR
		RTS				; ELSE RETURN

@ERRVAL:	JSR	ERVAL			; VALUE ERROR


; XPAASN -- Arithmetic Assignment Operator

XPAASN:		LDA	OPSTKX			; GET OP STACK INDEX
		CMP	#$FF			; AT STACK START
		BNE	@AAMAT			; BR IF NOT, [MAT ASSIGN]
						;	DO SCALER ASSIGN
		JSR	ARGP2			; GO POP TO P2 ARGS
		LDX	#5			; MOVE FR1 VALUE
@AASN1:		LDA	FR1,X			; TO FR0
		STA	FR0,X
		DEX
		BPL	@AASN1
		JMP	RTNVAR			; FR0 TO VVT & RETURN

@AAMAT:		LDA	#$80			; SET ASSIGN FLAG BIT ON
		STA	ADFLAG			; IN ASSIGN/DIM FLAG
		RTS				; GO POP REM OFF OPS


; XPACOM -- Array Comma Operator

XPACOM:		INC	COMCNT			; INCREMENT COMMA COUNT

;
; XPRPRN -- Right Parenthesis Operator
;	XPFLPRN - FUNCTION RIGHT PAREN OPERATOR
;
XPRPRN:
XPFLPRN:	LDY	OPSTKX
		PLA
		PLA
		JMP	_EXOPOP

; XPDLPRN -- DIM Left Parenthesis Operator

XDPSLP:
XPDLPRN:	LDA	#$40			; SET DIM FLAG BIT
		STA	ADFLAG			; IN ADFLAG
						;	FALL THRU TO XPALPRN

; XPALPRN -- Array Left Parenthesis Operator

XPALPRN:	BIT	ADFLAG
		BPL	@ALP1

		LDA	ARSLVL
		STA	ATEMP
		DEC	ARSLVL

@ALP1:		LDA	#0
		TAY
		CMP	COMCNT
		BEQ	@ALP2

		DEC	COMCNT
		JSR	GTINTO
		LDA	FR0+1
		BMI	@ALPER
		LDY	FR0

@ALP2:		STA	INDEX2+1
		STY	INDEX2
		JSR	GTINTO
		LDA	FR0
		STA	ZTEMP1
		LDA	FR0+1
		BMI	@ALPER
		STA	ZTEMP1+1
		JSR	ARGPOP
		BIT	ADFLAG
		BVC	@ALP3
		LDA	#0
		STA	ADFLAG
		RTS

@ALP3:		ROR	VTYPE
		BCS	@ALP4
@ALPER:		JSR	ERRDIM

@ALP4:		LDA	ZTEMP1+1
		CMP	VTYPE+EVAD1+1
		BCC	@ALP5
		BNE	@ALPER
		LDA	ZTEMP1
		CMP	VTYPE+EVAD1
		BCS	@ALPER

@ALP5:		LDA	INDEX2+1
		CMP	VTYPE+EVAD2+1
		BCC	@ALP6
		BNE	@ALPER
		LDA	INDEX2
		CMP	VTYPE+EVAD2
		BCS	@ALPER

@ALP6:		JSR	AMUL1
		LDA	INDEX2
		LDY	INDEX2+1
		JSR	AADD
		JSR	AMUL2
		LDA	FR0
		LDY	FR0+1
		JSR	AADD
		LDA	STARP
		LDY	STARP+1
		JSR	AADD

		BIT	ADFLAG
		BPL	@ALP8

		LDA	ATEMP
		STA	ARSLVL
		JSR	ARGPOP

		LDY	#5
@ALP7:		LDA	FR0,Y
		STA	(ZTEMP1),Y
		DEY
		BPL	@ALP7
		INY
		STY	ADFLAG
		RTS
@ALP8:		LDY	#5
@ALP9:		LDA	(ZTEMP1),Y
		STA	FR0,Y
		DEY
		BPL	@ALP9
		INY
		STY	VTYPE
		JMP	ARGPUSH

; XPSLPRN -- String Left Parenthesis

XPSLPRN:	LDA	COMCNT
		BEQ	@XSLP2

		JSR	@XSPV
		STY	INDEX2+1
		STA	INDEX2

@XSLP2:		JSR	@XSPV
		SEC
		SBC	#1
		STA	ZTEMP1
		TYA
		SBC	#0
		STA	ZTEMP1+1
		JSR	ARGPOP
		LDA	ADFLAG
		BPL	@XSLP3
		ORA	COMCNT
		STA	ADFLAG
		LDY	VTYPE+EVSDIM+1
		LDA	VTYPE+EVSDIM
		JMP	@XSLP4

@XSLP3:		LDA	VTYPE+EVSLEN
		LDY	VTYPE+EVSLEN+1

@XSLP4:		LDX	COMCNT
		BEQ	@XSLP6
		DEC	COMCNT
		CPY	INDEX2+1
		BCC	@XSLER
		BNE	@XSLP5
		CMP	INDEX2
		BCC	@XSLER

@XSLP5:		LDY	INDEX2+1
		LDA	INDEX2

@XSLP6:		SEC
		SBC	ZTEMP1
		STA	VTYPE+EVSLEN
		TAX
		TYA
		SBC	ZTEMP1+1
		STA	VTYPE+EVSLEN+1
		BCC	@XSLER
		TAY
		BNE	@XSLP7
		TXA
		BEQ	@XSLER

@XSLP7:		JSR	GSTRAD
		CLC
		LDA	VTYPE+EVSADR
		ADC	ZTEMP1
		STA	VTYPE+EVSADR
		LDA	VTYPE+EVSADR+1
		ADC	ZTEMP1+1
		STA	VTYPE+EVSADR+1

		BIT	ADFLAG
		BPL	@XSLP8
		RTS

@XSLP8:		JMP	ARGPUSH

@XSLER:		JSR	ERRSSL

;
; XSPV -- Pop Index Value as Integer and Insure Not Zero
;
@XSPV:		JSR	GTINTO
		LDA	FR0
		LDY	FR0+1
		BNE	@XSPVR
		TAX
		BEQ	@XSLER
@XSPVR:		RTS

;
; XSAASN -- String Assign Operator
;
XSAASN:		JSR	AAPSTR
RISASN:		LDA	VTYPE+EVSADR
		STA	MVFA
		LDA	VTYPE+EVSADR+1
		STA	MVFA+1
		LDA	VTYPE+EVSLEN
		STA	MVLNG
		LDY	VTYPE+EVSLEN+1
		STY	MVLNG+1
		LDY	OPSTKX
		CPY	#$FF
		BEQ	@XSA1
		LDA	#$80
		STA	ADFLAG
		JSR	_EXOPOP
		LDA	VTYPE+EVSLEN+1
		LDY	VTYPE+EVSLEN
		ROL	ADFLAG
		BCS	@XSA2A

@XSA1:		JSR	AAPSTR
		LDA	VTYPE+EVSDIM+1
		LDY	VTYPE+EVSDIM

@XSA2A:		CMP	MVLNG+1
		BCC	@XSA3
		BNE	@XSA4
		CPY	MVLNG
		BCS	@XSA4
@XSA3:		STA	MVLNG+1
		STY	MVLNG

@XSA4:		CLC
		LDA	VTYPE+EVSADR
		ADC	MVLNG
		TAY
		LDA	VTYPE+EVSADR+1
		ADC	MVLNG+1
		TAX

		SEC
		TYA
		SBC	STARP
		STA	ZTEMP3
		TXA
		SBC	STARP+1
		STA	ZTEMP3+1

		SEC
		LDA	#0
		SBC	MVLNG
		STA	MVLNG

		SEC
		LDA	MVFA
		SBC	MVLNG
		STA	MVFA
		LDA	MVFA+1
		SBC	#0
		STA	MVFA+1

		SEC
		LDA	VTYPE+EVSADR
		SBC	MVLNG
		STA	MVTA
		LDA	VTYPE+EVSADR+1
		SBC	#0
		STA	MVTA+1

		JSR	FMOVER

		LDA	VNUM
		JSR	GETVAR

		SEC
		LDA	ZTEMP3
		SBC	VTYPE+EVSADR
		TAY
		LDA	ZTEMP3+1
		SBC	VTYPE+EVSADR+1
		TAX

		LDA	#2
		AND	ADFLAG
		BEQ	@XSA5
		LDA	#0
		STA	ADFLAG

		CPX	VTYPE+EVSLEN+1
		BCC	@XSA6
		BNE	@XSA5
		CPY	VTYPE+EVSLEN
		BCS	@XSA5
@XSA6:		RTS

@XSA5:		STY	VTYPE+EVSLEN
		STX	VTYPE+EVSLEN+1
		JMP	RTNVAR
;
; AMUL2 -- Integer Multiplication of ZTEMP1 by 6
;
AMUL2:		ASL	ZTEMP1
		ROL	ZTEMP1+1
		LDY	ZTEMP1+1
		LDA	ZTEMP1
		ASL	ZTEMP1
		ROL	ZTEMP1+1
;
; AADD -- Integer Addition of [A,Y] to ZTEMP1
;
AADD:		CLC
		ADC	ZTEMP1
		STA	ZTEMP1
		TYA
		ADC	ZTEMP1+1
		STA	ZTEMP1+1
		RTS
;
; AMUL -- Integer Multiplication of ZTEMP1 by DIM2
;
AMUL1:		LDA	#0
		STA	ZTEMP4
		STA	ZTEMP4+1
		LDY	#$10

@AM1:		LDA	ZTEMP1
		LSR
		BCC	@AM3
		CLC
		LDX	#$FE
@AM2:		LDA	ZTEMP4+2,X
		ADC	VTYPE+EVAD2+2,X
		STA	ZTEMP4+2,X
		INX
		BNE	@AM2

@AM3:		LDX	#3
@AM4:		ROR	ZTEMP1,X

		DEX
		BPL	@AM4

		DEY
		BNE	@AM1

		RTS
;
; STRCMP -- String Compare
;
STRCMP:		JSR	AAPSTR
		JSR	MV0TO1
		JSR	AAPSTR
@SC1:		LDX	#FR0-2+EVSLEN
		JSR	ZPADEC
		PHP
		LDX	#FR1-2+EVSLEN
		JSR	ZPADEC
		BEQ	@SC2
		PLP
		BEQ	@SCLT

		LDY	#0
		LDA	(FR0-2+EVSADR),Y
		CMP	(FR1-2+EVSADR),Y
		BEQ	@SC3
		BCC	@SCLT

@SCGT:		LDA	#1
		RTS

@SCLT:		LDA	#$80
		RTS

@SC2:		PLP
		BNE	@SCGT
		RTS
@SC3:		INC	FR0-2+EVSADR
		BNE	@SC4
		INC	FR0-1+EVSADR
@SC4:		INC	FR1-2+EVSADR
		BNE	@SC1
		INC	FR1-1+EVSADR
		BNE	@SC1
;
; ZPADEC -- Decrement a Zero-Page Double Word
;
ZPADEC:		LDA	0,X
		BNE	@ZPAD1
		LDA	1,X
		BEQ	@ZPADR
		DEC	1,X
@ZPAD1:		DEC	0,X
		TAY
@ZPADR:		RTS

;
; Functions
;

; XPLEN -- Length Function

XPLEN:		JSR	AAPSTR
		LDA	VTYPE+EVSLEN
		LDY	VTYPE+EVSLEN+1
XPIFP:		STA	FR0
		STY	FR0+1
XPIFP1:		JSR	IFP
XPIFP2:		LDA	#0
		STA	VTYPE
		STA	VNUM
		JMP	ARGPUSH

; XPPEEK -- PEEK Function

XPPEEK:		JSR	GTINTO
		LDY	#0
		LDA	(FR0),Y
		JMP	XPIFP

; XPFRE -- FRE Function

XPFRE:		JSR	ARGPOP
		SEC
		LDA	HIMEM
		SBC	MEMTOP
		STA	FR0
		LDA	HIMEM+1
		SBC	MEMTOP+1
		STA	FR0+1
		JMP	XPIFP1

; XPVAL -- VAL Function

XPVAL:		JSR	SETSEOL

		LDA	#0
		STA	CIX
		JSR	CVAFP
; Restore Character
		JSR	RSTSEOL

		BCC	XPIFP2

@VERR:		JSR	ERSVAL


; XPASC -- ASC Function

XPASC:		JSR	AAPSTR
; Get 1>T Byte of St
		LDY	#0
		LDA	(FR0),Y
		JMP	XPIFP

; XPADR -- ADR Function

XPADR:		JSR	AAPSTR
		JMP	XPIFP1

; XPPDL -- Function Paddle

XPPDL:		LDA	#0		; evaluate PADDLE()
		BEQ	_GRF

; XPSTICK -- Function Joystick

XPSTICK:	LDA	#8		; evaluate STICK()
		BNE	_GRF

; XPPTRIG -- Function Paddle Trigger

XPPTRIG:	LDA	#12		; evaluate PTRIG()
		BNE	_GRF

; XPSTRIG -- Function Joystick Trigger

XPSTRIG:	LDA	#20		; evaluate STRIG()

_GRF:		PHA
		JSR	GTINTO
		LDA	FR0+1
		BNE	@ERGRF
		LDA	FR0

		PLA
		CLC
		ADC	FR0
		TAX

		LDA	GRFBAS,X
		LDY	#0
		BEQ	XPIFP

@ERGRF:		JSR	ERVAL

; XPSTR -- STR Function

XPSTR:		JSR	ARGPOP

		JSR	CVFASC

; Build String Element

		LDA	INBUFF
		STA	FR0-2+EVSADR
		LDA	INBUFF+1
		STA	FR0-1+EVSADR

		LDY	#$FF
@XSTR1:		INY
		LDA	(INBUFF),Y
		BPL	@XSTR1
		AND	#$7F
		STA	(INBUFF),Y
		INY
		STY	FR0-2+EVSLEN
		BNE	_CHR

; XPCHR -- CHR Function

XPCHR:		JSR	ARGPOP
		JSR	CVFPI
		LDA	FR0
		STA	LBUFF+$40

; Build String Element

		LDA	#>(LBUFF+$40)
		STA	FR0-1+EVSADR
		LDA	#<(LBUFF+$40)
		STA	FR0-2+EVSADR
		LDA	#1
		STA	FR0-2+EVSLEN
_CHR:		LDA	#0
		STA	FR0-1+EVSLEN
		STA	VNUM
		LDA	#EVSTR+EVSDTA+EVDIM
		STA	VTYPE
		JMP	ARGPUSH

; XPRND -- RND Function

XPRND:		LDX	#<RNDDIV
		LDY	#>RNDDIV
		JSR	FLD1R

		JSR	ARGPOP

		LDY	RNDLOC
		STY	FR0
		LDY	RNDLOC
		STY	FR0+1
		JSR	CVIFP
		JSR	FRDIV

		JMP	ARGPUSH

RNDDIV:		.byte	$42,$06,$55,$36,0,0

; XPABS -- ABS Function

XPABS:		JSR	ARGPOP
		LDA	FR0
		AND	#$7F
		STA	FR0
		JMP	ARGPUSH

; XPUSR -- USR Function

XPUSR:		JSR	@USR
		JSR	CVIFP
		JMP	ARGPUSH
@USR:
		LDA	COMCNT
		STA	ZTEMP2
@USR1:
		JSR	GTINTO
		DEC	ZTEMP2
		BMI	@USR2
		LDA	FR0
		PHA
		LDA	FR0+1
		PHA
		JMP	@USR1
@USR2:
		LDA	COMCNT
		PHA
		JMP	(FR0)

; XPINT -- INT Function

XPINT:		JSR	ARGPOP
		JSR	XINT
		JMP	ARGPUSH

; XINT -- Take Integer Part of FR0

XINT:		LDA	FR0
		AND	#$7F
		SEC
		SBC	#$3F

		BPL	@XINT1
		LDA	#0

@XINT1:		TAX
		LDA	#0
		TAY
@INT2:
		CPX	#FMPREC
		BCS	@XINT3
		ORA	FR0M,X
		STY	FR0M,X
		INX
		BNE	@INT2
@XINT3:
		LDX	FR0
		BPL	@XINT4
		TAX
		BEQ	@XINT4
;
;	# IS NEGATIVE AND NOT A WHOLE # [ADD -1]
		LDX	#$E0
		JSR	ZF1
		LDA	#$C0
		STA	FR1
		LDA	#1
		STA	FR1+1
		.if	BASIC_REVISION > 3
		jmp	FRADD
		nop
		.else
		JSR	FRADD		; ADD IT
		RTS
		.endif
@XINT4:
		JMP	NORM

; XPSIN -- Sine Function

XPSIN:		JSR	ARGPOP
		JSR	SIN
		.if	BASIC_REVISION = 1
		BCS	_TBAD
		BCC	_TGOOD
		.else
		jmp	_TEVAL
		.endif

; XPCOS -- Cosine Function

XPCOS:		JSR	ARGPOP
		JSR	COS
		.if	BASIC_REVISION = 1
		BCS	_TBAD
		BCC	_TGOOD
		.else
		jmp	_TEVAL
		.endif

; XPATN -- Arc Tangent Function

XPATN:		JSR	ARGPOP
		JSR	ATAN
		.if	BASIC_REVISION = 1
		BCS	_TBAD
		BCC	_TGOOD
		.else
		jmp	_TEVAL
		.endif

		.if	BASIC_REVISION = 1

; XPLOG -- LOG Function

XPLOG:		JSR	ARGPOP
		JSR	LOG
		BCS	_TBAD
		BCC	_TGOOD

; XPL10 -- LOG Base 10

XPL10:		JSR	ARGPOP
		JSR	LOG10
		BCS	_TBAD
		BCC	_TGOOD

		.else

; XPLOG -- LOG Function

XPLOG:		jsr	ARGPOP
		lda	FR0
		beq	_TBAD
		jsr	LOG
LOGCHK:		bcs	_TBAD
		lda	FR0
		eor	#$3B
		bne	_TGOOD
		lda	FR0+1
		and	#$F8
		bne	_TGOOD
		sta	FR0
		beq	_TGOOD

; XPL10 -- LOG Base 10

XPL10:		jsr	ARGPOP		; evaluate CLOG()
		lda	FR0
		beq	_TBAD
		jsr	LOG10
		jmp	LOGCHK

		.endif

; XPEXP -- EXP Function

XPEXP:		JSR	ARGPOP
		JSR	EXP
		.if	BASIC_REVISION = 1
		BCS	_TBAD
		BCC	_TGOOD
		.else
		jmp	_TEVAL
		.endif

		.if	BASIC_REVISION = 1

; XPSQR -- Square Root Function

XPSQR:		JSR	ARGPOP
		JSR	SQR
		BCS	_TBAD

;	FALL THREE TO _TGOOD

_TGOOD:		JMP	ARGPUSH

_TBAD:		JSR	ERVAL

; XPPOWER -- Exponential Operator [A**B]

XPPOWER:	JSR	ARGP2		;GET ARGUMENT IN FR0,FR1
		LDA	FR0		;IS BASE = 0 ?
		BNE	@N0		;IF BASE NOT 0, BRANCH
		LDA	FR1		;TEST EXPONENT
		BEQ	@P0		;IF = 0 ; BRANCH
		BPL	_TGOOD		;IF >0, ANSWER = 0
		BMI	_TBAD		;IF <0, VALUE ERROR
@P0:
		JMP	XTRUE		;IF =0, ANSWER = 1
@N0:
		BPL	@SPEVEN		; IF BASE + THEN NO SPECIAL PROCESS

		AND	#$7F		; AND OUT SIGN BIT
		STA	FR0		; SET AS BASE EXPONENT

		LDA	FR1		; GET EXPONENT OF POWER
		AND	#$7F		; AND OUT SIGN BIT
		SEC
		SBC	#$40		; IS POWER <1?
		BMI	_TBAD		; IF YES, ERROR

		LDX	#6		; GET INDEX TO LAST DIGIT

		CMP	#5		; IF # CAN HAVE DECIMAL
		BCC	@SP4		; PORTION, THEN BR
		LDY	#1
		BNE	@SP3

@SP4:		STA	ZTEMP1		;
		SEC			;
		LDA	#5		;
		SBC	ZTEMP1		;
		TAY			;

@SP3:		DEX			;
		DEY			;
		BEQ	@SP2		;
		LDA	FR1,X		;
		BNE	_TBAD		;
		BEQ	@SP3		;

@SP2:		LDY	#$80		;
		LDA	FR1,X		;
		LSR			;
		BCS	@POWR		;

@SPEVEN:	LDY	#0		;
@POWR:		TYA			;
		PHA			;

; Save Exponent [from FR1]

		LDX	#FMPREC		;
@POWR1:		LDA	FR1,X		;
		PHA			;
		DEX			;
		BPL	@POWR1		;

		JSR	LOG10		;
		BCS	_TBAD		;

; Pull Exponent into FR1 [from CPU Stack]

		LDX	#0		;
		LDY	#FMPREC		;
@POWR2:		PLA			;
		STA	FR1,X		;
		INX			;
		DEY			;
		BPL	@POWR2		;

		JSR	FRMUL		;
		JSR	EXP10		;
		BCS	EROV		;

		PLA			;
		BPL	_TGOOD		;

		ORA	FR0		;
		STA	FR0		;
		BNE	_TGOOD		;

		.else	; BASIC_REVISION > 1

XPSQR:		jsr	ARGPOP		; evaluate SQR()
		jsr	SQR
_TEVAL:		bcc	_TGOOD
_TBAD:		jsr	ERVAL

XPPOWER:	jsr	ARGP2
		lda	FR1
		beq	_XPP1
		rol
		ldy	FR0
		bne	_XPP2
		bcs	_TBAD
_TGOOD:		jmp	ARGPUSH
_XPP1:		jmp	XTRUE
_XPP2:		ldx	#$D4
		jsr	BA76
		ror
		pha
		ldx	#$E0
		jsr	BA76
		tya
		bpl	_XPP5
		and	#$7F
		sta	FR0
		bcs	_XPP3
		pla
		bcc	_TBAD
_XPP3:		lda	FR1
		bpl	_XPP4
		clc
_XPP4:		php
		ldx	$F7
		cpx	#5
		bcs	_XPP7
		lda	$E1,X
		ror
		bcc	_XPP7
		lda	#$80
		bne	_XPP8
_XPP5:		lda	$E0
		bpl	_XPP6
		clc
_XPP6:		php
_XPP7:		lda	#0
_XPP8:		pha
		ldx	#5

@XPP9:		lda	FR1,X
		pha
		dex
		bpl	@XPP9
		jsr	LOG10
		ldx	#0
		ldy	#5
@XPP10:		pla
		sta	FR1,X
		inx
		dey
		bpl	@XPP10
		jsr	FRMUL
		jsr	EXP10
		bcs	EROV
		pla
		ora	FR0
		sta	FR0
		plp
		pla
		bpl	_TGOOD
		bcc	_TGOOD
		ldx	#$D4
		jsr	BA76
		bcs	_TGOOD
		lda	FR0
		sec
		and	#$7F
		sbc	#$3F
		cmp	#6
		bcs	@XPOUT
		tax
		tay
		sed
		sec
@XPACC:		lda	FR0,X
		adc	#0
		sta	FR0,X
		dex
		bne	@XPACC
		cld
		bcc	@XPP11
		inc	FR0
		inc	FR0+1
@XPP11:		iny
		cpy	#6
		bcs	@XPOUT
		stx	FR0,Y
		bcc	@XPP11
@XPOUT:		jmp	ARGPUSH

		.endif	; BASIC_REVISION > 1

EROV:		JSR	EROVFL

; XDIM & XCOM -- Execute DIM and COMMON Statements

;DIM:
XDIM:
XCOM:		ldy	STINDEX
		cpy	NXTSTD
		bcc	@DC2
		rts
@DC2:		jsr	XLET
		lda	$D2
		ror
		bcc	B218
B215:		jsr	ERRDIM
B218:		sec
		rol
		sta	$D2
		bmi	B24C
		ldy	$F5
		ldx	$F6
		iny
		bne	B228
		inx
		bmi	B215
B228:		sty	$D6
		stx	$D7
		sty	$F5
		stx	$F6
		ldy	$97
		ldx	$98
		iny
		bne	B23A
		inx
		bmi	B215
B23A:		sty	$D8
		stx	$D9
		jsr	AMUL1
		jsr	AMUL2
		ldy	$F5
		lda	$F6
		bmi	B215

		.if	BASIC_REVISION = 1
		jmp	B260
		.else
		bpl	B260
		.endif

B24C:		lda	#0
		sta	$D6
		sta	$D7
		ldy	$F5
		sty	$D8
		lda	$F6
		sta	$D9
		bne	B260
		cpy	#0
		beq	B215
B260:		ldx	#$8E
		jsr	EXPAND
		sec
		lda	$97
		sbc	STARP
		sta	FR0
		lda	$98
		sbc	$8D
		sta	FR0+1
		jsr	RTNVAR
		jmp	XDIM

		; Execute POKE

XPOKE:		jsr	GETINT
		lda	FR0
		sta	POKADR
		lda	FR0+1
		sta	POKADR+1
		jsr	GET1INT
		lda	FR0
		ldy	#0
		sta	(POKADR),Y
		rts

		; Execute DEG

XDEG:		lda	#6

		.if	BASIC_REVISION = 1
		sta	$FB
		rts
		.else
		bne	B293
		.endif

		; Execute RAD

XRAD:		lda	#0
B293:		sta	$FB
		rts

		; Execute RESTORE

XREST:		lda	#0
		sta	DATAD
		jsr	B904
		bcc	B2A2
		tay
		beq	B2A9
B2A2:		jsr	GETPINT
		lda	FR0+1
		ldy	FR0
B2A9:		sta	DATALN+1
		sty	DATALN
		rts

		; Execute READ

XREAD:		lda	STINDEX
		pha
		jsr	B6F9
		lda	DATALN
		sta	$A0
		lda	DATALN+1
		sta	$A1
		jsr	GETSTMT
		lda	STMCUR
		sta	INBUFF
		lda	STMCUR+1
		sta	INBUFF+1
		jsr	XRTN
		pla
		sta	STINDEX
B2CD:		ldy	#0
		sty	CIX
		jsr	B32F
		sta	DATALN
		jsr	B32D
		sta	DATALN+1
		jsr	B32D
		sta	$F5
B2E0:		jsr	B32D
		sta	$F6
		jsr	B32D

		.if	BASIC_REVISION = 1
		cmp	#1
		.else
		eor	#1
		.endif

		beq	B312
		ldy	$F6
		cpy	$F5
		bcs	B2F7
		dey
		sty	CIX
		bcc	B2E0
B2F7:		sty	CIX
		dec	CIX
B2FB:		ldy	#1
		lda	(INBUFF),Y
		bmi	B33B
		sec
		lda	CIX
		adc	INBUFF
		sta	INBUFF
		lda	#0
		sta	DATAD
		adc	INBUFF+1
		sta	INBUFF+1
		bcc	B2CD

B312:		.if	BASIC_REVISION = 1
		lda	#0
		.endif

		sta	$F5
B314:		lda	$F5
		cmp	DATAD
		bcs	B325
B31A:		jsr	B32D
		bne	B31A
		bcs	B2FB
		inc	$F5
		bne	B314
B325:		lda	#$40
		sta	DIRFLG
		inc	CIX

		.if	BASIC_REVISION = 1
		jmp	B35F
		.else
		bcs	B35F
		.endif

B32D:		inc	CIX
B32F:		ldy	CIX
		lda	(INBUFF),Y
		cmp	#CRPRN
		clc
		beq	B33A
		cmp	#CR
B33A:		rts
B33B:		jsr	ERROOD

		; Execute INPUT

XINPUT:		lda	#$3F
		sta	$C2
		jsr	_EGTOKEN
		dec	$A8
		bcc	B34E
		jsr	BD07
		sta	$B4
B34E:		jsr	INTLBF

		.if	BASIC_REVISION = 1
		jsr	BA89
		jsr	B378
		.else
		jsr	BDE4
		jsr	TSTBRK
		beq	B378
		.endif

		ldy	#0
		sty	DIRFLG
		sty	CIX
B35F:		jsr	_EGTOKEN
		inc	$A8
		lda	$D2
		bmi	B382
		jsr	AFP
		bcs	B37B
		jsr	B32F
		bne	B37B
		jsr	RTNVAR
		jmp	B3AD

B378:		.if	BASIC_REVISION = 1
		jsr	TSTBRK
		bne	@1
		rts
		.endif
@1:		jmp	XSTOP

B37B:		lda	#0
		sta	$B4
		jsr	ERRINP
B382:		jsr	EXPINT
		jsr	ARGPUSH
		dec	CIX
		lda	CIX
		sta	$F5
		ldx	#$FF
B390:		inx
		jsr	B32D
		bne	B390
		bcs	B39C
		bit	DIRFLG
		bvc	B390
B39C:		ldy	$F5
		lda	$A8
		pha
		txa
		ldx	#INBUFF
		jsr	RISC
		pla
		sta	$A8
		jsr	RISASN
B3AD:		bit	DIRFLG
		bvc	B3C0
		inc	DATAD
		jsr	B904
		bcs	B3C5
		jsr	B32F
		bcc	B3D5
		jmp	B2FB
B3C0:		jsr	B904
		bcc	B3CD
B3C5:		jsr	INTLBF
		lda	#0
		sta	$B4
		rts
B3CD:		jsr	B32F
		bcc	B3D5
		jmp	B34E
B3D5:		inc	CIX
		jmp	B35F

		; Execute PRINT, ?

XPRINT:		lda	PTABW
		sta	STENUM
		lda	#0
		sta	COX
B3E2:		ldy	$A8
		lda	(STMCUR),Y
		cmp	#$12
		beq	B449
		cmp	#$16
		.if	BASIC_REVISION = 1
		.byte	$f0,$7C
		.else
		beq	B467
		.endif
		cmp	#$14
		.if	BASIC_REVISION = 1
		.byte	$f0,$78
		.else
		beq	B467
		.endif
		cmp	#$15
		beq	B474
		cmp	#$1C
		beq	B46A
		jsr	XLET
		jsr	ARGPOP
		dec	$A8
		bit	$D2
		bmi	B428

		.if	BASIC_REVISION > 1
		lda	FR0+1
		cmp	#$10
		bcc	B412
		lda	$D9
		and	#$F0
		sta	$D9
		.endif

B412:		jsr	FASC
		lda	#0
		sta	CIX
B419:		ldy	CIX
		lda	(INBUFF),Y
		pha
		inc	CIX
		jsr	B48F
		pla
		bpl	B419
		bmi	B3E2
B428:		jsr	GSTRAD
		lda	#0
		sta	CIX
B42F:		lda	$D6
		bne	B437
		dec	$D7
		bmi	B3E2
B437:		dec	$D6
		ldy	CIX
		lda	(FR0),Y
		inc	CIX
		bne	B443
		inc	FR0+1
B443:		jsr	B491
		jmp	B42F
B449:		ldy	COX
		iny
		cpy	STENUM
		bcc	B459
		clc
		lda	PTABW
		adc	STENUM
		sta	STENUM
		bcc	B449
B459:		ldy	COX
		cpy	STENUM
		bcs	B474
		lda	#$20
		jsr	B48F
		jmp	B459

		.if	BASIC_REVISION > 1
B467:		jmp	B485
		.endif

B46A:		jsr	BD07
		sta	$B5
		dec	$A8
		jmp	B3E2
B474:		inc	$A8

		.if	BASIC_REVISION = 1
B467:		jmp	B3E2
		ldy	$A8
		dey
		lda	(STMCUR),Y
		cmp	#$15
		beq	B48A
		cmp	#$12
		beq	B48A
		.else
		ldy	$A8
		lda	(STMCUR),Y
		cmp	#$16
		beq	B48A
		cmp	#$14
		beq	B48A
		jmp	B3E2
		.endif

B485:		lda	#CR
		jsr	B491
B48A:		lda	#0
		sta	$B5
		rts
B48F:		and	#$7F
B491:		inc	COX
		jmp	BA99

		; Execute LPRINT

XLPRINT:	lda	#<@printerdev
		sta	INBUFF
		lda	#>@printerdev
		sta	INBUFF+1
		ldx	#7
		stx	$B5
		lda	#0
		ldy	#8
		jsr	BBD8
		jsr	BCBB
		jsr	XPRINT
		jmp	BCF7

@printerdev:	.byte	"P:",$9B

		; Execute LIST

XLIST:		ldy	#0
		sty	$A0
		sty	$A1
		dey
		sty	$AD
		lda	#$7F
		sta	$AE
		sta	$2FE
		lda	#CR
		jsr	BA99
		jsr	B6F9
@1:		ldy	$A8
		iny
		cpy	$A7
		bcs	@4
		lda	$A8
		pha
		jsr	POP1
		pla
		sta	$A8
		lda	$D2
		bpl	@2
		jsr	BACF
		jmp	@1

@2:		jsr	GETPINT
		sta	$A1
		lda	FR0
		sta	$A0
		ldy	$A8
		cpy	$A7
		beq	@3
		jsr	GETPINT
@3:		lda	FR0
		sta	$AD
		lda	FR0+1
		sta	$AE
@4:		jsr	GETSTMT
@5:		jsr	TENDST
		bmi	@7
		ldy	#1
		lda	(STMCUR),Y
		cmp	$AE
		bcc	@6
		bne	@7
		dey
		lda	(STMCUR),Y
		cmp	$AD
		bcc	@6
		bne	@7
@6:		jsr	LLINE
		jsr	TSTBRK

		.if	BASIC_REVISION = 1
		bne	@7
		.else
		beq	@7
		.endif

		jsr	GETLL
		jsr	GNXTL
		jmp	@5
@7:		lda	$B5
		beq	@8

		jsr	BCF7
		lda	#0
		sta	$B5
@8:		sta	$2FE
		jmp	XRTN

B53E:		stx	$AA
		jsr	@5
@1:		ldy	$AA
		dec	STENUM
		bmi	@4
@2:		lda	(POKADR),Y
		bmi	@3
		iny
		bne	@2
@3:		iny
		jsr	@4
		jmp	@1

@4:		clc
		tya
		adc	POKADR
		sta	POKADR
		tay
		lda	POKADR+1
		adc	#0
@5:		sta	POKADR+1
		sty	POKADR
		rts

outstr:		ldy	#$FF
		sty	STENUM
@1:		inc	STENUM
		ldy	STENUM
		lda	(POKADR),Y
		pha
		cmp	#CR
		beq	@2
		and	#$7F
		beq	@3
@2:		jsr	BA99
@3:		pla
		bpl	@1
		rts

B581:		lda	#$20
		jsr	BA99
B586:		jsr	outstr
		lda	#$20
		jmp	BA99

LLINE:		ldy	#0
		lda	(STMCUR),Y
		sta	FR0
		iny
		lda	(STMCUR),Y
		sta	FR0+1
		jsr	IFP
		jsr	FASC
		lda	INBUFF
		sta	POKADR
		lda	INBUFF+1
		sta	POKADR+1
		jsr	B586
LDLINE:		ldy	#2
		lda	(STMCUR),Y
		sta	MAXCIX
		iny
@loop_y:	lda	(STMCUR),Y
		sta	$A7
		iny
		sty	$A8
		jsr	B5C2
		ldy	$A7
		cpy	MAXCIX
		bcc	@loop_y
		rts

B5C2:		jsr	B663
		cmp	#$36
		beq	B5E0
		jsr	B66F
		jsr	B663
		cmp	#CERR
		beq	@1
		cmp	#2
		bcs	B5E0
@1:		jsr	B661
		jsr	BA99
		jmp	@1

B5E0:		jsr	B661
		bpl	@1
		and	#$7F
		sta	STENUM
		ldx	#0
		lda	VNTP+1
		ldy	VNTP
		jsr	B53E
		jsr	outstr
		cmp	#$A8
		bne	B5E0
		jsr	B661
		jmp	B5E0
@1:		cmp	#15
		beq	@3
		bcs	@6
		jsr	NCTOFR0
		dec	$A8
		jsr	FASC
		lda	INBUFF
		sta	POKADR
		lda	INBUFF+1
		sta	POKADR+1
@2:		jsr	outstr
		jmp	B5E0
@3:		jsr	B661
		sta	STENUM
		lda	#$22
		jsr	BA99
		lda	STENUM
		beq	@5
@4:		jsr	B661
		jsr	BA99
		dec	STENUM
		bne	@4
@5:		lda	#$22
		jsr	BA99
		jmp	B5E0
@6:		sec
		sbc	#$10
		sta	STENUM
		ldx	#0
		lda	#>OPNTAB
		ldy	#<OPNTAB
		jsr	B53E
		jsr	B663
		cmp	#$3D
		bcs	@2
		ldy	#0
		lda	(POKADR),Y
		and	#$7F
		jsr	TSALPH
		bcs	@2
		jsr	B581
		jmp	B5E0

B661:		inc	$A8
B663:		ldy	$A8
		cpy	$A7
		bcs	B66C
		lda	(STMCUR),Y
		rts

B66C:		pla
		pla
		rts

B66F:		sta	STENUM
		ldx	#2
		lda	#>SNTAB
		ldy	#<SNTAB
		jsr	B53E
		jmp	B586

		; Execute FOR

XFOR:		jsr	B883
		jsr	XLET
		lda	$D3
		ora	#$80
		pha
		jsr	B823
		lda	#$C
		jsr	B871
		jsr	POP1
		ldx	#$D4
		ldy	#0
		jsr	B888
		jsr	ZFR0
		lda	#1
		sta	FR0+1
		lda	#$40
		sta	FR0
		jsr	B904
		bcs	@1
		jsr	POP1
@1:		ldx	#$D4
		ldy	#6
		jsr	B888
		pla
B6B5:		pha
		lda	#4
		jsr	B871
		pla
		ldy	#0
		sta	($C4),Y
		lda	(STMCUR),Y
		iny
		sta	($C4),Y
		lda	(STMCUR),Y
		iny
		sta	($C4),Y
		ldx	SVONTX
		dex
		txa
		iny
		sta	($C4),Y
		rts

		; Execute GOSUB

XGOSUB:		jsr	B6F9

		; Execute GOTO, GO TO

XGOTO:		jsr	GETPINT
B6D8:		lda	FR0+1
		sta	$A1
		lda	FR0
		sta	$A0
B6E0:		jsr	GETSTMT
		bcs	B6EA
		pla
		pla
		jmp	EXECNL

B6EA:		jsr	B6F0
		jsr	ERRNOLN
B6F0:		lda	SAVCUR
		sta	STMCUR
		lda	SAVCUR+1
		sta	STMCUR+1
		rts
B6F9:		jsr	B883
B6FC:		lda	#0

		.if	BASIC_REVISION = 1
		jmp	B6B5
		.else
		beq	B6B5
		.endif

		; Execute NEXT

XNEXT:		ldy	$A8
		lda	(STMCUR),Y
		sta	$C7
@1:		jsr	XPOP
		bcs	B749
		beq	B749
		cmp	$C7
		bne	@1
		ldy	#6
		jsr	B897
		lda	$E0
		pha
		lda	$C7
		jsr	_EGTVAR
		jsr	FRADD
		jsr	RTNVAR
		ldy	#0
		jsr	B897
		pla
		bpl	B732
		jsr	FRCMP
		bpl	B73A
		rts

B732:		jsr	FRCMP
		beq	B73A
		bmi	B73A
B739:		rts

		.if	BASIC_REVISION = 1

B73A:		lda	#$10
		jsr	B871
		jsr	YYY
		cmp	#8
		.byte	$d0,$32
		rts

B749:		jsr	ERNOFOR

		; Execute RETURN

XRTN:		jsr	XPOP
		.byte	$b0,$16
		bne	XRTN
		jsr	YYY
		cmp	#12
		beq	@1
		cmp	#$1E
		beq	@1
		cmp	#4
		beq	@1
		cmp	#34
		bne	zzz
@1:		rts

		jsr	ERBRTN
YYY:		jsr	B816
		bcs	zzz
		ldy	$b2
		dey
		lda	($8A),Y
		sta	$A7
		iny
		lda	($8A),Y
		rts

zzz:		jsr	B6F0
		jsr	ERGFDEL

		; Execute RUN

XRUN:		jsr	B904
		bcs	B754
		jsr	BAF7
B754:
		.else

B73A:		lda	#$10
		jsr	B871
		jsr	BDCB
		cmp	#8
		beq	B739
		jmp	BDC2
B749:		jsr	ERNOFOR

		; Execute RUN

XRUN:		jsr	B904
		bcs	B754
		jsr	BAF7
B754:		nop

		.endif

		lda	#0
		sta	$A0
		sta	$A1
		jsr	B816
		jsr	TENDST
		bmi	B775
		jsr	RUNINIT

		; Execute CLR

XCLR:		jsr	B8B9
		jsr	B8A8
		lda	#0
		sta	DATALN
		sta	DATALN+1
		sta	DATAD
		rts

B775:		jmp	SNX1

		; Execute IF

XIF:		jsr	POP1
		lda	FR0+1
		beq	B787
		jsr	B904

		.if	BASIC_REVISION = 1
		bcs	@1
		jmp	XGOTO
@1:		rts
		.else
		bcs	B78B
		jmp	XGOTO
		.endif

B787:		lda	MAXCIX
		sta	$A7
B78B:		rts

		; Execute END

XEND:		jsr	B7A6
		jmp	SNX1

		; Execute STOP

XSTOP:		jsr	B7A6
		jsr	BD79

		lda	#<STOPPED_STR
		sta	POKADR
		lda	#>STOPPED_STR
		sta	POKADR+1

		jsr	outstr
		jmp	B968
B7A6:		jsr	TENDST
		bmi	B7B2
		sta	STOPLN+1
		dey
		lda	(STMCUR),Y
		sta	STOPLN
B7B2:		jmp	SETDZ

		.if	BASIC_REVISION = 1
STOPPED_STR:	BasicString "STOPPED "
		.endif

		; Execute CONT

XCONT:		jsr	TENDST
		bpl	B7B2
		lda	STOPLN
		sta	$A0
		lda	STOPLN+1
		sta	$A1
		jsr	GETSTMT
		jsr	TENDST
		bmi	B775
		jsr	GETLL
		jsr	GNXTL
		jsr	TENDST
		bmi	B775
		jmp	SETLN1

		; Execute TRAP

XTRAP:		jsr	GETINT
		lda	FR0
		sta	$BC
		lda	FR0+1
		sta	$BD
		rts

		; Execute ON

XON:		jsr	B883
		jsr	GET1INT
		lda	FR0
		.if	BASIC_REVISION = 1
		.byte	$f0,$20
		.else
		beq	B811
		.endif
		ldy	$A8
		dey
		lda	(STMCUR),Y
		cmp	#$17
		.if	BASIC_REVISION > 1
		php
		.endif
		beq	B7FB
		jsr	B6FC
B7FB:		lda	FR0
		sta	SVONTX
B7FF:		jsr	GETPINT
		dec	SVONTX
		.if	BASIC_REVISION = 1
		.byte	$f0,$06
		.else
		beq	B812
		.endif
		jsr	B904
		bcc	B7FF
		.if	BASIC_REVISION = 1
B811:
B812:
		rts
		jmp	B6D8
		rts
		.else
		plp
		beq	B811
		jsr	XPOP
B811:		rts
B812:		plp
		jmp	B6D8
		.endif

B816:		jsr	GETSTMT
SETLN1:		ldy	#2
		lda	(STMCUR),Y
		sta	MAXCIX
		iny
		sty	$A7
		rts
B823:		sta	$C7
		jsr	B87A
B828:		jsr	XPOP
		bcs	B835
		beq	B835
		cmp	$C7
		.if	BASIC_REVISION = 1
		.byte	$f0,$0B
		.else
		beq	B83D
		.endif
		bne	B828

B835:		lda	$C4
		sta	MEMTOP
		lda	$C5
		sta	MEMTOP+1
B83D:		rts

		.if	BASIC_REVISION = 1
		rts
		.endif

		; Execute POP

XPOP:		lda	RUNSTK+1
		cmp	MEMTOP+1
		.if	BASIC_REVISION = 1
		.byte	$90,$08
		.else
		bcc	B84A
		.endif
		lda	RUNSTK
		cmp	MEMTOP

		.if	BASIC_REVISION = 1
		.byte	$90,$02
B84A:		sec
		rts
		lda	#4
		jsr	B872
		.else
		bcs	B83D
B84A:		lda	#4
		ldx	#$90
		jsr	CONTLOW
		.endif

		ldy	#3
		lda	(MEMTOP),Y
		sta	SVONTL
		dey
		lda	(MEMTOP),Y
		sta	$A1
		dey
		lda	(MEMTOP),Y
		sta	$A0
		dey
		lda	(MEMTOP),Y
		beq	B86F
		pha
		lda	#12

		.if	BASIC_REVISION > 1
		ldx	#$90
		.endif

		.if	BASIC_REVISION = 1
		jsr	B872
		.else
		jsr	CONTLOW
		.endif

		pla
B86F:		clc
		rts

B872:		.if	BASIC_REVISION = 1
		tay
		ldx	#$90
		jmp	CONTLOW
		.endif

B871:		jsr	B87A
		tay
		ldx	#$90
		jmp	EXPLOW
B87A:		ldx	MEMTOP
		stx	$C4
		ldx	MEMTOP+1
		stx	$C5
		rts
B883:		ldy	$A8
		sty	SVONTX
		rts

B888:		lda	#6
		sta	$C6
B88C:		lda	0,X
		sta	($C4),Y
		inx
		iny
		dec	$C6
		bne	B88C
		rts

B897:		lda	#$6
		sta	$C6
		ldx	#$E0
B89D:		lda	(MEMTOP),Y
		sta	$0,X
		inx
		iny
		dec	$C6
		bne	B89D
		rts

B8A8:		lda	STARP
		sta	RUNSTK
		sta	MEMTOP
		sta	APMH
		lda	STARP+1
		sta	RUNSTK+1
		sta	MEMTOP+1
		sta	APMH+1
		rts

B8B9:		ldx	VVTP
		stx	$F5
		ldy	VVTP+1
		sty	$F6
B8C1:		ldx	$F6
		cpx	STMTAB+1
		bcc	B8CE
		ldx	$F5
		cpx	STMTAB
		bcc	B8CE
		rts

B8CE:		ldy	#0
		lda	($F5),Y
		and	#$FE
		sta	($F5),Y
		ldy	#2
		ldx	#6
		lda	#0
B8DC:		sta	($F5),Y
		iny
		dex
		bne	B8DC
		lda	$F5
		clc
		adc	#8
		sta	$F5
		lda	$F6
		adc	#0
		sta	$F6
		bne	B8C1

		; fill B6..BB -> 0

RUNINIT:	.if	BASIC_REVISION = 1

		ldy	#0
		sty	$BA
		sty	$BB
		sty	$B9
		sty	$FB
		sty	$B6
		sty	$B7
		sty	$B8
		dey
		sty	$BD
		sty	$11
		.else
		ldx	#5
		ldy	#0
B8F5:		sty	$B6,X
		dex
		bpl	B8F5

		sty	$FB
		dey
		sty	$BD
		sty	BRKKEY
		.endif

		jmp	CLSALL

B904:		ldx	$A8
		inx
		cpx	$A7
		rts

ERRNSF:		inc	ERRNUM		; FILE NOT SAVE FILE		21 = Bad LOAD
ERRDNO:		inc	ERRNUM		; #DN0 > 7			20 = Bad Device #
ERRPTL:		inc	ERRNUM		; LOAD PGM TOO BIG		19 = Insufficient RAM
ERSVAL:		inc	ERRNUM		; STRING NOT VALID		18 = Bad string / val
XERR:		inc	ERRNUM		;EXECUTION OF GARBAGE		17 = Bad line - "ERROR -  "; execute "ERROR-"
ERBRTN:		inc	ERRNUM		; BAD RETURNS			16 = RETURN without GOSUB
ERGFDEL:	inc	ERRNUM		; GOSUB/FOR LINE DELETED	15 = Deleted NEXT/RETURN
ERLTL:		inc	ERRNUM		; LINE TOO LONG			14 = Statement Too Long / Complex
ERNOFOR:	inc	ERRNUM		; NO MATCHING FOR		13 = NEXT without FOR
ERRNOLN:	inc	ERRNUM		; LINE NOT FOUND [GOSUB/GOTO]	12 = Line Not Found
EROVFL:		inc	ERRNUM		; FLOATING POINT OVERFLOW	11 = FP Overflow
ERRAOS:		inc	ERRNUM		; ARG STACK OVERFLOW		10 = Too many GOSUBs
ERRDIM:		inc	ERRNUM		; ARRAY/STRING DIM ERROR	 9 = DIM error
ERRINP:		inc	ERRNUM		; INPUT STMT ERROR		 8 = INPUT, READ type mismatch
ERRLN:		inc	ERRNUM		;VALUE NOT <32768		 7 = Bad Value
ERROOD:		inc	ERRNUM		; READ OUT OF DATA		 6 = Out of DATA
ERRSSL:		inc	ERRNUM		; STRING LENGTH ERROR		 5 = String overflow
ERRVSF:		inc	ERRNUM		; VARIABLE TABLE FULL		 4 = Out of Variables
ERVAL:		inc	ERRNUM		; VALUE ERROR			 3 = Out of Range
MEMFULL:	inc	ERRNUM		; MEMORY FULL			 2 = Memory Full
ERON:		inc	ERRNUM		; NO LINE # FOR EXP IN ON	 1 = Line Not Found for ON EXP

;
; Error Routine
;
ERROR:		lda	#0
		sta	$2FE
		jsr	B7A6
		lda	$BD
		bmi	@1
		sta	$A1
		lda	$BC
		sta	$A0
		lda	#$80
		sta	$BD
		lda	$B9
		sta	ERRSAVE
		lda	#0
		sta	$B9
		jmp	B6E0
@1:		jsr	BD79
		lda	#CERR
		jsr	B66F
		lda	$B9
		sta	FR0
		lda	#0
		sta	FR0+1
		jsr	B993
B968:		jsr	TENDST
		bmi	@1
		lda	#<ATLINE_STR
		sta	POKADR
		lda	#>ATLINE_STR
		sta	POKADR+1
		jsr	outstr
		ldy	#1
		lda	(STMCUR),Y
		sta	FR0+1
		dey
		lda	(STMCUR),Y
		sta	FR0
		jsr	B993
@1:		jsr	BD79
		lda	#0
		sta	$B9
		.if	BASIC_REVISION > 1
		jsr	SETDZ
		.endif
		jmp	SYNTAX

B993:		jsr	IFP
		jsr	FASC
		lda	INBUFF
		sta	POKADR
		lda	INBUFF+1
		sta	POKADR+1
		.if	BASIC_REVISION = 1
		jsr	outstr
		rts
		.else
		jmp	outstr
		.endif

ATLINE_STR:	BasicString " AT LINE "

		; Execute SETCOLOR

XSETCOLOR:	jsr	GET1INT
		lda	FR0
		cmp	#5
		bcs	B9D0
		pha
		jsr	GETINT
		lda	FR0
		asl
		asl
		asl
		asl
		pha
		jsr	GETINT
		pla
		clc
		adc	FR0
		tay
		pla
		tax
		tya
		sta	$2C4,X
		rts

B9D0:		jsr	ERVAL

		; Execute SOUND

XSOUND:		jsr	GET1INT
		lda	FR0
		cmp	#4
		bcs	B9D0
		asl
		pha
		lda	#0
		sta	AUDCTL
		lda	#3
		sta	SKCTL
		jsr	GETINT
		pla
		pha
		tax
		lda	FR0
		sta	$D200,X
		jsr	GETINT
		lda	FR0
		asl
		asl
		asl
		asl
		pha
		jsr	GETINT
		pla
		tay
		pla
		tax
		tya
		clc
		adc	FR0
		sta	$D201,X
		rts

		; Execute POSITION

XPOS:		jsr	GETINT
		lda	FR0
		sta	$55
		lda	FR0+1
		sta	$56
		jsr	GET1INT
		lda	FR0
		sta	$54
		rts

		; Execute COLOR

XCOLOR:		jsr	GETINT
		lda	FR0
		sta	$C8
		rts

		; Execute DRAWTO

XDRAWTO:	jsr	XPOS
		lda	$C8
		sta	$2FB
		lda	#$11
		ldx	#6
		jsr	BABE
		lda	#12
		sta	$34A,X
		lda	#0
		sta	$34B,X
		jsr	BD29
		jmp	BCBB

		; Execute GRAPHICS

XGR:		ldx	#6
		stx	$C1
		jsr	BCF7
		jsr	GETINT
		ldx	#<@screendev
		ldy	#>@screendev
		stx	INBUFF
		sty	INBUFF+1
		ldx	#6
		lda	FR0
		and	#$F0
		eor	#$1C
		tay
		lda	FR0
		jsr	BBD8
		jmp	BCBB

@screendev:	.byte	"S:",$9B

		; Execute PLOT

XPLOT:		jsr	XPOS
		lda	$C8
		ldx	#6
		jmp	BA9B

BA76:		.if	BASIC_REVISION = 1

		ldx	$B4
		bne	GLGO
		lda	#CR
		jsr	BA99
BA89:		ldx	$B4
		bne	GLGO
		lda	$C2
		jsr	BA99
GLGO:		ldx	$B4
		lda	#5
		jsr	BABE
		jsr	BD0F
		jmp	BCBB

		.else
		sec
		lda	0,X
		and	#$7F
		sbc	#$40
		bcc	@rts
		sta	$F5
		sta	$F7
		txa
		adc	$F5
		inx
		inx
		inx
		inx
		inx
		inx
		stx	$F5
		tax
@loop:		inx
		cpx	$F5
		bcs	@rts
		lda	0,X
		beq	@loop
@rts:		rts

		.endif

BA99:		ldx	$B5
BA9B:		pha
		jsr	BAC0
		lda	$34A,X
		sta	ICAX1Z
		lda	$34B,X
		sta	ICAX2Z
		pla
		tay
		jsr	BAB2
		tya
		jmp	BCBE

BAB2:		lda	$347,X
		pha
		lda	$346,X
		pha
		tya
		ldy	#MEOLFLG
		rts

BABE:		sta	$C0
BAC0:		stx	$C1
		jmp	BCAF

		; Execute ENTER

XENTER:		lda	#4
		jsr	BAD7
		sta	$B4
		jmp	SYNTAX

BACF:		lda	#8
		jsr	BAD7
		sta	$B5
		rts

BAD7:		pha
		ldy	#7
		sty	$C1
		jsr	BCAF
		lda	#12
		jsr	BD2B
		ldy	#3
		sty	$C0
		pla
		ldy	#0
		jsr	BC02
		lda	#7
		rts

		.if	BASIC_REVISION > 1
FP_two:		.byte	$40,$02,$00,$00,$00,$00
		.endif

BAF7:		lda	#$FF
		bne	W1

		; Execute LOAD

XLOAD:		lda	#0
W1:		pha
		lda	#4
		jsr	BAD7
		pla
W2:		pha
		lda	#7
		sta	$C0
		sta	LOADFLG
		jsr	BCAF
		ldy	#14
		jsr	BD15
		jsr	BCBB
		lda	LBUFF
		ora	LBUFF+1
		bne	@7
		ldx	#$8C
@3:		clc
		lda	LOMEM
		adc	$500,X
		.if	BASIC_REVISION > 1
		php
		clc
		.if	BASIC_REVISION > 2
		adc	#0
		.else
		adc	#$10
		.endif
		.endif
		tay
		lda	LOMEM+1
		adc	$501,X
		.if	BASIC_REVISION > 1
		plp
		adc	#0
		.endif
		cmp	HIMEM+1
		bcc	@5
		bne	@4
		cpy	HIMEM
		bcc	@5
@4:		jmp	ERRPTL
@5:		sta	1,X
		sty	0,X
		dex
		dex
		cpx	#VNTP
		bcs	@3
		jsr	W9
		jsr	XCLR
		lda	#0
		sta	LOADFLG
		pla
		beq	@6
		rts
@6:		jmp	SNX1

@7:		lda	#0
		sta	LOADFLG
		jsr	ERRNSF

		.if	BASIC_REVISION > 1

		; Execute CLOAD

XCLOAD:		lda	#4
		jsr	BBB4
		lda	#0
		beq	W2
		.endif

		; Execute SAVE

XSAVE:		lda	#8
		jsr	BAD7
BB72:		lda	#$B
		sta	$C0
		ldx	#$80
@8:		sec
		lda	0,X
		sbc	LOMEM
		sta	$500,X
		inx
		lda	0,X
		sbc	LOMEM+1
		sta	$500,X
		inx
		cpx	#$8E
		bcc	@8
		jsr	BCAF
		ldy	#$E
		jsr	BD15
		jsr	BCBB
W9:		jsr	BCAF
		lda	VNTP
		sta	INBUFF
		lda	VNTP+1
		sta	INBUFF+1
		ldy	$58D
		dey
		tya
		ldy	$58C
		jsr	BD17
		jsr	BCBB
		jmp	BCF7

BBB4:
		.if	BASIC_REVISION = 1

		; Execute CSAVE

XCSAVE:		lda	#8
		jsr	ZZZ
		jmp	BB72


		; Execute CLOAD

XCLOAD:		lda	#4
		jsr	ZZZ
		lda	#0
		jmp	W2

		.else

		nop
		nop

		.endif

ZZZ:		pha
		ldx	#<BBCE
		stx	INBUFF
		ldx	#>BBCE
		stx	INBUFF+1
		ldx	#7
		pla
		tay
		lda	#$80
		jsr	BBD8
		jsr	BCBB
		lda	#7
		rts

BBCE:		.byte	"C:",$9B

		.if	BASIC_REVISION > 1

		; Execute CSAVE

XCSAVE:		lda	#8
		jsr	BBB4
		bne	BB72
		.endif

BBD8:		pha
		lda	#3
		jsr	BABE
		pla
		sta	$34B,X
		tya
		sta	$34A,X
		jsr	BD1E
		jmp	INTLBF

		; Execute XIO

XXIO:		jsr	BD09
		jmp	BBF4

		; Execute OPEN

XOPEN:		lda	#3
BBF4:		sta	$C0
		jsr	BCA8
		jsr	BD09
		pha
		jsr	BD09
		tay
		pla
BC02:		pha
		tya
		pha
		jsr	XLET
		jsr	SETSEOL
		jsr	BCAF
		pla
		sta	$34B,X
		pla
		sta	$34A,X
		jsr	BD0F
		jsr	RSTSEOL
		jsr	INTLBF
		jmp	BCBB

		; Execute CLOSE

XCLOSE:		lda	#12
BC24:		sta	$C0
		jsr	BCA8
BC29:		jsr	BD29
		jmp	BCBB

		; Execute STATUS

XSTATUS:	jsr	BCA8
		lda	#13
		jsr	BD2B
		jsr	BD00
		jmp	BD31

		; Execute NOTE

XNOTE:		lda	#$26
		jsr	BC24
		lda	$34C,X
		ldy	$34D,X
		jsr	BD33
		jsr	BCAF
		lda	$34E,X
		jmp	BD31

		; Execute POINT

XPOINT:		jsr	BCA8
		jsr	GETPINT
		jsr	BCAF
		lda	FR0
		sta	$34C,X
		lda	FR0+1
		sta	$34D,X
		jsr	GETPINT
		jsr	BCAF
		lda	FR0
		sta	$34E,X
		lda	#$25
		sta	$C0
		.if	BASIC_REVISION = 1
		jmp	BC29
		.else
		bne	BC29
		.endif

		; Execute PUT

XPUT:		jsr	BCA8
		jsr	GETINT
		lda	FR0
		ldx	$C1
		jmp	BA9B

		; Execute GET

XGET:		.if	BASIC_REVISION > 1
		jsr	INTLBF
		.endif
		jsr	BCA8
BC8B:		lda	#7
		sta	$C0
		ldy	#1
		jsr	BD15
		jsr	BCBB
		ldy	#0
		lda	(INBUFF),Y
		jmp	BD31

		; Execute LOCATE

XLOCATE:	jsr	XPOS
		ldx	#6
		jsr	BAC0
		bne	BC8B
BCA8:		jsr	BD07
		sta	$C1
		beq	BCB8
BCAF:		lda	$C1
		asl
		asl
		asl
		asl
		tax
		.if	BASIC_REVISION = 1
		.byte	$30,$01
		.else
		bpl	BD06
		.endif
		.if	BASIC_REVISION = 1
		rts
		.endif
BCB8:		jsr	ERRDNO
BCBB:		jsr	BD00
BCBE:		.if	BASIC_REVISION = 1
		.byte	$30,$01
		rts
		.else
		bpl	BD06
		.endif
		ldy	#0
		sty	$2FE
		cmp	#$80
		bne	BCD2
		sty	BRKKEY
		lda	LOADFLG
		.if	BASIC_REVISION = 1
		.byte	$f0,$03
		.else
		beq	BD06
		.endif
		jmp	COLDSTART

		.if	BASIC_REVISION = 1
		rts
		.endif

BCD2:		ldy	$C1
BCD3:		cmp	#$88
		beq	BCE7
BCD8:		sta	$B9
		cpy	#7
		bne	BCE1
		jsr	BCF7
BCE1:		jsr	SETDZ
		jmp	ERROR
BCE7:		cpy	#7
		bne	BCD8
		ldx	#$5D
		cpx	$C2
		bne	BCD8
		jsr	BCF7
		jmp	SNX2
BCF7:		jsr	BCAF
		beq	BD06
		lda	#12
		.if	BASIC_REVISION = 1
		jmp	BD2B
		.else
		bne	BD2B
		.endif
BD00:		jsr	BCAF
		lda	ICSTA,X
BD06:		rts

BD07:		inc	$A8
BD09:		jsr	GETPINT
		lda	FR0
		rts
BD0F:		ldy	#$FF
		bne	BD15
		ldy	#0
BD15:		lda	#0
BD17:		sta	ICBLH,X
		tya
		sta	ICBLL,X
BD1E:		lda	INBUFF+1
		ldy	INBUFF
		sta	ICBAH,X
		tya
		sta	ICBAL,X
BD29:		lda	$C0
BD2B:		sta	ICCOM,X
		.if	BASIC_REVISION = 1
		jsr	CIOV
		rts
		.else
		jmp	CIOV
		.endif
BD31:		ldy	#0
BD33:		pha
		tya
		pha
		jsr	POP1
		pla
		sta	FR0+1
		pla
		sta	FR0
		jsr	IFP
		jmp	RTNVAR

CLSALL:		lda	#0
		ldx	#7
BD49:		sta	$D200,X
		dex
		bne	BD49
		ldy	#7
		sty	$C1
BD53:		jsr	BCF7
		dec	$C1
		bne	BD53
		rts

		.if	BASIC_REVISION > 1
SETDZ:		lda	#0
		sta	$B4
		sta	$B5
		rts
		.endif

PREADY:		ldx	#6
BD64:		stx	CIX
		lda	BD72,X
		jsr	BA99
		ldx	CIX
		dex
		bpl	BD64
		rts

BD72:		.byte	$9B,"YDAER",$9B

BD79:		ldx	#0
		beq	BD64

		.if	BASIC_REVISION = 1
SETDZ:		lda	#0
		sta	$B4
		sta	$B5
		rts
		.endif

SETSEOL:		jsr	AAPSTR
		lda	FR0
		sta	INBUFF
		lda	FR0+1
		sta	INBUFF+1
		ldy	FR0+2
		ldx	FR0+3
		beq	BD90
		ldy	#$FF
BD90:		lda	(INBUFF),Y
		sta	$97
		sty	$98
		lda	#CR
		sta	(INBUFF),Y
		sta	MEOLFLG
		rts
RSTSEOL:	ldy	$98
		lda	$97
		sta	(INBUFF),Y
		lda	#0
		sta	MEOLFLG
		rts

		.if	BASIC_REVISION = 1

		.byte	$20

		.else

		; Execute RETURN

XRTN:		jsr	XPOP
		bcs	BDC8
		bne	XRTN
		jsr	BDCB
		cmp	#12
		beq	BDDA
		cmp	#$1E
		beq	BDDA
		cmp	#4
		beq	BDDA
		cmp	#$22
		beq	BDDA
BDC2:		jsr	B6F0
		jsr	ERGFDEL
BDC8:		jsr	ERBRTN
BDCB:		jsr	B816
		bcs	BDC2
		ldy	SVONTL
		dey
		lda	(STMCUR),Y
		sta	$A7
		iny
		lda	(STMCUR),Y
BDDA:		rts

		ldx	$B4
		bne	GLGO2
		lda	#CR
		jsr	BA99
BDE4:		ldx	$B4
		bne	GLGO2
		lda	$C2
		jsr	BA99
GLGO2:		ldx	$B4
		lda	#5
		jsr	BABE
		jsr	BD0F
		jmp	BCBB

XPPLUS:		jsr	ARGP2
		jsr	FRADD
		jmp	ARGPUSH

		.endif

BE03:		sec
		rts

SIN:		lda	#4
		bit	FR0
		bpl	BE11
		lda	#2
		bne	BE11
COS:		lda	#1
BE11:		sta	$F0
		lda	FR0
		and	#$7F
		sta	FR0
		.if	BASIC_REVISION = 1
		lda	#$5F
		.else
		lda	#$BD
		.endif
		clc
		adc	$FB
		tax
		ldy	#$BE
		jsr	FLD1R
		jsr	FDIV
		bcc	@1
		rts
@1:		lda	FR0
		and	#$7F
		sec
		sbc	#$40
		bmi	@4
		cmp	#4
		bpl	BE03
		tax
		lda	FR0+1,X
		sta	$F1
		and	#$10
		beq	@2
		lda	#2
@2:		clc
		adc	$F1
		and	#3
		adc	$F0
		sta	$F0
		stx	$F1
		jsr	MV0TO1
		ldx	$F1
		lda	#0
@3:		sta	$E2,X
		inx
		cpx	#3
		bcc	@3
		jsr	FSUB
@4:		lsr	$F0
		bcc	@5
		jsr	MV0TO1
		ldx	#<BECF
		ldy	#>BECF
		jsr	FLD0R
		jsr	FSUB
@5:		ldx	#$E6
		ldy	#5
		jsr	FSTOR
		jsr	MV0TO1
		jsr	FMUL
		bcs	BE03
		lda	#6
		ldx	#<BE9F
		ldy	#>BE9F
		jsr	PLYEVL
		ldx	#$E6
		ldy	#5
		jsr	FLD1R
		jsr	FMUL
		lsr	$F0
		bcc	@rts
		clc
		lda	FR0
		beq	@rts
		eor	#$80
		sta	FR0
@rts:		rts

BE9F:		.byte	$BD,$03,$55,$14,$99,$39
		.byte	$3E,$01,$60,$44,$27,$52
		.byte	$BE,$46,$81,$75,$43,$55
		.byte	$3F,$07,$96,$92,$62,$39
		.byte	$BF,$64,$59,$64,$08,$67
		.byte	$40,$01,$57,$07,$96,$32	;  1.57079632
		.byte	$40,$90,$00,$00,$00,$00	; 90.00000000
BEC9:		.byte	$3F,$01,$74,$53,$29,$25
BECF:		.byte	$40,$01,$00,$00,$00,$00	;  1.00000000

ATAN:		lda	#0
		sta	$F0
		sta	$F1
		lda	FR0
		and	#$7F
		cmp	#$40
		bmi	@1
		lda	FR0
		and	#%10000000
		sta	$F0
		inc	$F1
		lda	#%01111111
		and	FR0
		sta	FR0
		ldx	#<__DFEA
		ldy	#>__DFEA
		jsr	__DE95
@1:		ldx	#$E6
		ldy	#5
		jsr	FSTOR
		jsr	MV0TO1
		jsr	FMUL
		bcs	@rts
		lda	#11
		ldx	#<__DFAE
		ldy	#>__DFAE
		jsr	PLYEVL
		bcs	@rts
		ldx	#$E6
		ldy	#5
		jsr	FLD1R
		jsr	FMUL
		bcs	@rts
		lda	$F1
		beq	@2
		ldx	#$F0
		ldy	#$DF
		jsr	FLD1R
		jsr	FADD
		lda	$F0
		ora	FR0
		sta	FR0
@2:		lda	$FB
		beq	@rts
		ldx	#<BEC9
		ldy	#>BEC9
		jsr	FLD1R
		jsr	FDIV
@rts:		rts

BF41:		sec
		rts

SQR:		lda	#0
		sta	$F1
		lda	FR0
		bmi	BF41
		cmp	#$3F
		beq	@2
		clc
		adc	#1
		sta	$F1
		sta	$E0
		lda	#1
		sta	$E1
		ldx	#4
		lda	#0
@1:		sta	$E2,X
		dex
		bpl	@1
		jsr	FDIV
@2:		lda	#6
		sta	$EF
		ldx	#$E6
		ldy	#5
		jsr	FSTOR
		jsr	MV0TO1
		ldx	#<FP_two
		ldy	#>FP_two
		jsr	FLD0R
		jsr	FSUB
		ldx	#$E6
		ldy	#5
		jsr	FLD1R
		jsr	FMUL
@3:		ldx	#$EC
		ldy	#5
		jsr	FSTOR
		jsr	MV0TO1
		ldx	#$E6
		ldy	#5
		jsr	FLD0R
		jsr	FDIV
		ldx	#$EC
		ldy	#5
		jsr	FLD1R
		jsr	FSUB
		ldx	#<__DF6C
		ldy	#>__DF6C
		jsr	FLD1R
		jsr	FMUL
		lda	FR0
		beq	@4
		ldx	#$EC
		ldy	#5
		jsr	FLD1R
		jsr	FADD
		dec	$EF
		bpl	@3
@4:		ldx	#$EC
		ldy	#5
		jsr	FLD0R
		lda	$F1
		BEQ	@SQROUT
		sec
		sbc	#$40
		clc
		ror
		clc
		adc	#$40
		and	#$7F
		sta	$E0
		lda	$F1
		ror
		lda	#1
		bcc	@5
		lda	#$10
@5:		sta	$E1
		ldx	#4
		lda	#0
@6:		sta	$E2,X
		dex
		bpl	@6
 		jsr	FMUL

		.if	BASIC_REVISION > 1
		EntryPoint(BFF0)
		.endif
@SQROUT:	rts

		.if	BASIC_REVISION = 1
FP_two:		.byte	$40,$02,$00,$00,$00,$00
		.byte	$30,$30,$20,$20,$60,$70,$70
		.byte	$00,$00,$00,$00,$30,$30,$3C,$7C,$7C,$7C,$64,$64,$67,$E7,$C0,$C0
		.byte	$80,$80,$E0,$E0,$00,$00,$00,$00,$30,$30,$38,$38,$38,$38,$FC,$EC
		.byte	$EC,$0C,$04,$06,$06,$02,$03,$03,$00,$00,$00,$00,$30,$30,$30,$B0
		.byte	$B0,$D8,$F8,$78,$38,$18,$18,$18,$10,$10,$1C,$1C,$00,$00,$00,$00
		.byte	$30,$30,$30,$30,$30,$30,$30,$30,$20,$E0,$E0,$80,$80,$00,$00,$00
		.endif

		.if	BASIC_REVISION = 1
		EntryPoint(BFF0)
		.byte	$00,$00,$00,$00,$CC,$B8,$A4,$90,$A0
ENTRY1:		rts
		.endif

		.if	BASIC_REVISION = 2
		.byte	$00,$00,$2C,$37,"inner"	; prehistoric debris!
		.endif

		.res	BFFA-*

		EntryPoint(BFFA)
		.word	COLDSTART
		EntryPoint(BFFC)
		.word	$0500
		EntryPoint(BFFE)
		.if	BASIC_REVISION = 1
		.word	ENTRY1
		.else
		.word	BFF0
		.endif

		.end
